begin;
update public.business_hours set opens_at='00:00',closes_at='23:59:59',is_closed=false;
insert into auth.users(id,email,email_confirmed_at) values('aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','qa-owner@example.test',now()),('bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb','qa-counter@example.test',now());
insert into public.staff_memberships(business_id,user_id,role) values('11111111-1111-4111-8111-111111111111','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa','OWNER');
insert into public.invoice_settings(business_id,business_name) values('11111111-1111-4111-8111-111111111111','Italian Pizza') on conflict do nothing;
set local role authenticated;
select set_config('request.jwt.claim.sub','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',true);
select public.save_staff_by_email('11111111-1111-4111-8111-111111111111','22222222-2222-4222-8222-222222222222','qa-counter@example.test','CASHIER',true,array['pos.use','orders.read','receipts.print']);
select set_config('request.jwt.claim.sub','bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',true);
do $$ declare s public.register_shifts; sale jsonb;
begin
 s:=public.open_pos_shift('22222222-2222-4222-8222-222222222222',1000);
 if public.has_permission(s.business_id,'register.manage') then raise exception 'POS shift starter granted full register permission'; end if;
 if (public.open_pos_shift(s.branch_id,1000)).id<>s.id then raise exception 'POS shift retry failed'; end if;
 sale:=public.create_pos_order(jsonb_build_object('branchId',s.branch_id,'shiftId',s.id,'clientReference','qa-minimal-counter','cashReceived',1000,'items',jsonb_build_array(jsonb_build_object('productId','40000000-0000-4000-8000-000000000004','quantity',1,'modifiers','[]'::jsonb))));
 if (sale->>'total')::integer<>699 then raise exception 'Restricted counter cannot sell'; end if;
end $$;
select set_config('request.jwt.claim.sub','aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',true);
do $$ declare b uuid:='11111111-1111-4111-8111-111111111111'; v_order_id uuid; invoice_id uuid; inv jsonb; manual_id uuid; paid_id uuid; s public.register_shifts; draft jsonb; denied boolean:=false;
begin
 select id into v_order_id from public.orders where client_reference='qa-minimal-counter';
 invoice_id:=public.save_invoice(b,'{}',null,v_order_id);
 if public.save_invoice(b,'{}',null,v_order_id)<>invoice_id then raise exception 'Order invoice duplicated'; end if;
 inv:=public.invoice_document(invoice_id);
 if inv->>'status'<>'FINALIZED' or (inv->>'total')::integer<>699 or (inv->>'paid')::integer<>699 or inv->>'payment_status'<>'PAID' then raise exception 'Authoritative order invoice failed'; end if;
 if (select count(*) from public.payment_transactions p where p.order_id=v_order_id and business_id=b)<>1 then raise exception 'Order invoice duplicated ledger'; end if;
 draft:=jsonb_build_object('branch_id','22222222-2222-4222-8222-222222222222','customer_name','Manual customer','client_reference','qa-manual-stable','lines',jsonb_build_array(jsonb_build_object('description','Meal','quantity',2,'unit_price',500)));
 manual_id:=public.save_invoice(b,draft);
 if public.save_invoice(b,draft)<>manual_id then raise exception 'Manual invoice retry duplicated'; end if;
 perform public.transition_invoice(manual_id,'FINALIZE');
 s:=public.open_register_shift('22222222-2222-4222-8222-222222222222',0);
 paid_id:=public.record_invoice_payment(manual_id,1000,'CASH','qa-manual-cash');
 if (public.register_summary(s.id)->>'expected')::integer<>1000 then raise exception 'Manual cash missing from drawer'; end if;
 perform public.record_manual_refund(paid_id,1000,'Test cash returned');
 if (public.register_summary(s.id)->>'expected')::integer<>0 then raise exception 'Manual cash refund missing from drawer'; end if;
 perform public.transition_invoice(manual_id,'VOID','Refunded in full');
 draft:=draft||'{"client_reference":"qa-manual-bank"}'; manual_id:=public.save_invoice(b,draft);perform public.transition_invoice(manual_id,'FINALIZE');
 paid_id:=public.record_invoice_payment(manual_id,1000,'BANK_TRANSFER','qa-manual-bank-payment');
 perform public.record_manual_refund(paid_id,1000,'Confirmed bank transfer returned');
 if (public.invoice_document(manual_id)->>'paid')::integer<>0 then raise exception 'Manual bank refund mismatch'; end if;
 begin insert into storage.objects(bucket_id,name) values('product-images','99999999-9999-4999-8999-999999999999/unauthorized.png'); exception when insufficient_privilege then denied:=true; end;
 if not denied then raise exception 'Cross-business Storage write allowed'; end if;
 insert into storage.objects(bucket_id,name) values('product-images',b::text||'/qa/test.png');
 delete from storage.objects where name=b::text||'/qa/test.png';
end $$;
reset role;
select 'PASS: restricted POS sale/own shift, authoritative order invoice/ledger reuse, manual retry, cash/bank refunds, drawer reconciliation and Storage RLS' as result;
rollback;
