"use client"
/* eslint-disable react-hooks/set-state-in-effect -- debounced remote search and subscription bootstrap intentionally synchronize external state */

import Link from "next/link"
import { useRouter } from "next/navigation"
import { Menu, Search, X } from "lucide-react"
import { useCallback, useEffect, useRef, useState } from "react"
import type { AdminContext } from "@/lib/auth"
import { createClient } from "@/lib/supabase/client"
import { NotificationPopover } from "@/components/notification-popover"
import { playOrderNotificationSound, unlockOrderNotificationSound } from "@/lib/order-notification-sound"

type SearchRow={id:string;label:string;kind:"Order"|"Product"|"Customer";href:string}
export function AdminTopbar({context,onMenu,menuOpen}:{context:AdminContext;onMenu:()=>void;menuOpen:boolean}){
  const router=useRouter();const [busy,setBusy]=useState(false);const [branches,setBranches]=useState<Array<{id:string;name:string;restaurant_name?:string|null;city:string}>>([]);const [branch,setBranch]=useState("");const [query,setQuery]=useState("");const [results,setResults]=useState<SearchRow[]>([]);const [unread,setUnread]=useState(0);const [notificationRevision,setNotificationRevision]=useState(0);const searchRef=useRef<HTMLInputElement>(null);const searchRequest=useRef(0);const alertSettings=useRef({enabled:true,url:""})
  const refreshUnread=useCallback(async()=>{if(document.visibilityState!=="visible")return;const client=createClient();const [{count},{data:settings}]=await Promise.all([client.from("notifications").select("id",{count:"exact",head:true}).eq("business_id",context.businessId).eq("is_read",false).is("resolved_at",null),client.from("business_operating_settings").select("new_order_sound,order_notification_sound_url").eq("business_id",context.businessId).maybeSingle()]);alertSettings.current={enabled:settings?.new_order_sound??true,url:settings?.order_notification_sound_url??""};setUnread(count??0)},[context.businessId])
  useEffect(()=>{let active=true;const supabase=createClient();const loadBranches=async()=>{let request=supabase.from("branches").select("id,name,restaurant_name,city").eq("business_id",context.businessId).eq("is_active",true);if(context.role!=="OWNER"){if(!context.allowedBranchIds.length){setBranches([]);setBranch("");return}request=request.in("id",context.allowedBranchIds)}const {data}=await request.order("sort_order");if(!active)return;const list=(data??[]) as Array<{id:string;name:string;restaurant_name?:string|null;city:string}>;setBranches(list);const saved=decodeURIComponent(document.cookie.match(/(?:^|; )ip-admin-branch=([^;]+)/)?.[1]??"");const selected=saved==="all"&&context.role==="OWNER"?"all":saved&&list.some(item=>item.id===saved)?saved:list.length===1?list[0].id:"";setBranch(selected);if(selected&&saved!==selected)document.cookie=`ip-admin-branch=${selected}; Path=/; SameSite=Lax; Max-Age=31536000`};void loadBranches();const channel=supabase.channel(`admin-shell-${context.businessId}`).on("postgres_changes",{event:"*",schema:"public",table:"branches",filter:`business_id=eq.${context.businessId}`},()=>{void loadBranches();router.refresh()}).on("postgres_changes",{event:"INSERT",schema:"public",table:"notifications",filter:`business_id=eq.${context.businessId}`},payload=>{const row=payload.new as {notification_type?:string;resolved_at?:string|null};if(row.resolved_at)return;setNotificationRevision(value=>value+1);void refreshUnread();if(row.notification_type==="NEW_ORDER"&&alertSettings.current.enabled)void playOrderNotificationSound(alertSettings.current.url)}).on("postgres_changes",{event:"UPDATE",schema:"public",table:"notifications",filter:`business_id=eq.${context.businessId}`},()=>{setNotificationRevision(value=>value+1);void refreshUnread()}).subscribe();const onLocation=()=>{void loadBranches();router.refresh()};const unlock=()=>void unlockOrderNotificationSound();window.addEventListener("restaurant-location-updated",onLocation);window.addEventListener("pointerdown",unlock,{once:true});window.addEventListener("keydown",unlock,{once:true});const initial=window.setTimeout(()=>void refreshUnread(),0);const timer=window.setInterval(()=>void refreshUnread(),30000);const onVisibility=()=>{if(document.visibilityState==="visible")void refreshUnread()};document.addEventListener("visibilitychange",onVisibility);return()=>{active=false;void supabase.removeChannel(channel);window.removeEventListener("restaurant-location-updated",onLocation);window.removeEventListener("pointerdown",unlock);window.removeEventListener("keydown",unlock);window.clearTimeout(initial);window.clearInterval(timer);document.removeEventListener("visibilitychange",onVisibility)}},[context.allowedBranchIds,context.businessId,context.role,refreshUnread,router])
  useEffect(()=>{const shortcut=(event:KeyboardEvent)=>{if(((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==="k")||(event.key==="/"&&document.activeElement?.tagName!=="INPUT")){event.preventDefault();searchRef.current?.focus()}};window.addEventListener("keydown",shortcut);return()=>window.removeEventListener("keydown",shortcut)},[])
  useEffect(()=>{const trimmed=query.trim();if(trimmed.length<2){searchRequest.current+=1;setResults([]);return}const requestId=++searchRequest.current;const timer=window.setTimeout(async()=>{const supabase=createClient();const term=`%${trimmed.replace(/[^a-zA-Z0-9 @.+-]/g,"")}%`;const [orders,products,profiles]=await Promise.all([supabase.from("orders").select("id,order_number,customer_name").eq("business_id",context.businessId).or(`order_number.ilike.${term},customer_name.ilike.${term}`).limit(4),supabase.from("products").select("id,name").eq("business_id",context.businessId).ilike("name",term).limit(4),supabase.from("profiles").select("id,full_name").ilike("full_name",term).limit(4)]);if(requestId!==searchRequest.current)return;setResults([...(orders.data??[]).map(row=>({id:String(row.id),label:`${row.order_number} · ${row.customer_name}`,kind:"Order" as const,href:"/orders"})),...(products.data??[]).map(row=>({id:String(row.id),label:String(row.name),kind:"Product" as const,href:"/menu"})),...(profiles.data??[]).map(row=>({id:String(row.id),label:String(row.full_name??"Customer"),kind:"Customer" as const,href:"/customers"}))])},180);return()=>window.clearTimeout(timer)},[context.businessId,query])
  const selectBranch=(id:string)=>{setBranch(id);document.cookie=`ip-admin-branch=${id}; Path=/; SameSite=Lax; Max-Age=31536000`;window.dispatchEvent(new CustomEvent("admin-branch-change",{detail:id}));router.refresh()}
  const signOut=async()=>{setBusy(true);await createClient().auth.signOut({ scope: "local" });router.replace("/login");router.refresh()}
  return <header className="admin-topbar"><div className="admin-topbar__start"><button className="icon-action mobile-menu-button" type="button" onClick={onMenu} aria-label="Toggle navigation">{menuOpen?<X/>:<Menu/>}</button><label className="branch-select"><span>BRANCH</span><select value={branch} onChange={event=>selectBranch(event.target.value)} aria-label="Active branch"><option value="" disabled>Select branch</option>{context.role==="OWNER"&&<option value="all">All branches (reports)</option>}{branches.map(item=><option key={item.id} value={item.id} title={`${item.restaurant_name||item.name} — ${item.city}`}>{item.restaurant_name?`${item.restaurant_name} — ${item.city}`:item.name}</option>)}</select></label></div><div className="global-search"><Search aria-hidden="true"/><input ref={searchRef} value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search orders, products, customers" aria-label="Global search"/><kbd>⌘K</kbd>{results.length>0&&<div className="global-search__results">{results.map(result=><Link href={result.href} key={`${result.kind}-${result.id}`} onClick={()=>{setQuery("");setResults([])}}><small>{result.kind}</small><strong>{result.label}</strong></Link>)}</div>}</div><div className="admin-topbar__actions"><NotificationPopover businessId={context.businessId} unread={unread} onUnread={setUnread} revision={notificationRevision}/><div className="admin-topbar__identity"><strong>{context.email}</strong><small>{context.role}</small></div><button className="button button--outline signout-button" type="button" onClick={signOut} disabled={busy}>{busy?"Signing out…":"Sign out"}</button></div></header>
}
