"use client"

import { useState } from "react"
import { createClient } from "@/lib/supabase/client"

type Row={id:string;name:string;sku:string|null;base_price:number;sale_price:number|null;is_available:boolean;override?:{is_available:boolean|null;price_override:number|null;pos_visible:boolean|null;online_visible:boolean|null;stock_available:boolean|null;sort_order:number|null}}

export function BranchCatalogManager({businessId,branchId,branchName,initialRows}:{businessId:string;branchId:string;branchName:string;initialRows:Row[]}){
  const [rows,setRows]=useState(initialRows)
  const [busy,setBusy]=useState<string|null>(null)
  const [message,setMessage]=useState("")
  const update=(id:string,patch:Partial<NonNullable<Row["override"]>>)=>setRows(current=>current.map(row=>row.id===id?{...row,override:{is_available:row.override?.is_available??row.is_available,price_override:row.override?.price_override??null,pos_visible:row.override?.pos_visible??true,online_visible:row.override?.online_visible??true,stock_available:row.override?.stock_available??true,sort_order:row.override?.sort_order??null,...patch}}:row))
  const save=async(row:Row)=>{setBusy(row.id);setMessage("");const override=row.override??{is_available:row.is_available,price_override:null,pos_visible:true,online_visible:true,stock_available:true,sort_order:null};const {error}=await createClient().from("branch_product_overrides").upsert({business_id:businessId,branch_id:branchId,product_id:row.id,...override},{onConflict:"branch_id,product_id"});setBusy(null);setMessage(error?error.message:`${row.name} saved for ${branchName}.`)}
  const reset=async(row:Row)=>{setBusy(row.id);setMessage("");const {error}=await createClient().from("branch_product_overrides").delete().eq("business_id",businessId).eq("branch_id",branchId).eq("product_id",row.id);if(!error)setRows(current=>current.map(item=>item.id===row.id?{...item,override:undefined}:item));setBusy(null);setMessage(error?error.message:`${row.name} now uses the base catalog.`)}
  return <><div className="page-heading"><div><span className="eyebrow">BRANCH CATALOG</span><h1>{branchName}</h1><p>Keep one restaurant menu and override only price, visibility, stock and ordering for this branch.</p></div></div>{message&&<p className="inline-notice" role="status">{message}</p>}<section className="panel"><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Product</th><th>Branch price</th><th>Available</th><th>In stock</th><th>POS</th><th>Website</th><th>Order</th><th>Actions</th></tr></thead><tbody>{rows.map(row=>{const value=row.override;const checked=(key:"is_available"|"stock_available"|"pos_visible"|"online_visible",fallback:boolean)=>value?.[key]??fallback;return <tr key={row.id}><td data-label="Product"><strong>{row.name}</strong><small>{row.sku??"No SKU"} · Base Rs {(row.sale_price??row.base_price).toLocaleString("en-PK")}</small></td><td data-label="Branch price"><input type="number" min="0" placeholder="Use base" value={value?.price_override??""} onChange={event=>update(row.id,{price_override:event.target.value===""?null:Number(event.target.value)})}/></td>{([['is_available','Available',row.is_available],['stock_available','Stock',true],['pos_visible','POS',true],['online_visible','Website',true]] as const).map(([key,label,fallback])=><td key={key} data-label={label}><input type="checkbox" checked={checked(key,fallback)} onChange={event=>update(row.id,{[key]:event.target.checked})}/></td>)}<td data-label="Order"><input type="number" value={value?.sort_order??""} placeholder="Base" onChange={event=>update(row.id,{sort_order:event.target.value===""?null:Number(event.target.value)})}/></td><td data-label="Actions"><div className="table-actions"><button type="button" disabled={busy===row.id} onClick={()=>void save(row)}>Save</button>{value&&<button type="button" className="is-danger" disabled={busy===row.id} onClick={()=>void reset(row)}>Use base</button>}</div></td></tr>})}</tbody></table></div></section></>
}
