"use client"

import { useState } from "react"
import { useRouter } from "next/navigation"
import { Ban, ShieldCheck, X } from "lucide-react"
import { createClient } from "@/lib/supabase/client"

type CustomerIdentity={customer_id:string|null;name:string;email:string|null;phone:string|null;restriction_status:"ACTIVE"|"BLOCKED"}

export function CustomerRestrictionAction({businessId,customer,canManage}:{businessId:string;customer:CustomerIdentity;canManage:boolean}){
  const router=useRouter();const [open,setOpen]=useState(false);const [busy,setBusy]=useState(false);const [error,setError]=useState("");const [reason,setReason]=useState("REPEATED_FAKE_ORDERS");const [note,setNote]=useState("");const [preventOrders,setPreventOrders]=useState(true);const [preventAccess,setPreventAccess]=useState(true)
  if(!canManage)return <span className="status-badge">{customer.restriction_status}</span>
  const mutate=async(blocked:boolean)=>{setBusy(true);setError("");const {error}=await createClient().rpc("set_customer_restriction",{p_business_id:businessId,p_auth_user_id:customer.customer_id,p_email:customer.email,p_phone:customer.phone,p_blocked:blocked,p_reason_code:reason,p_internal_note:note,p_prevent_new_orders:preventOrders,p_prevent_storefront_access:preventAccess});setBusy(false);if(error)setError(blocked?"Customer could not be restricted. Please retry.":"Customer access could not be restored. Please retry.");else{setOpen(false);router.refresh()}}
  const unblock=()=>{if(window.confirm("Restore access for "+customer.name+"?"))void mutate(false)}
  return <>{customer.restriction_status==="BLOCKED"?<button className="button button--outline" disabled={busy} onClick={unblock}><ShieldCheck/>Unblock</button>:<button className="button button--outline" disabled={busy} onClick={()=>setOpen(true)}><Ban/>Block</button>}{error&&<small className="danger-text" role="alert">{error}</small>}{open&&<div className="drawer-backdrop" onMouseDown={event=>{if(event.target===event.currentTarget)setOpen(false)}}><section className="editor customer-block-editor" role="dialog" aria-modal="true" aria-labelledby="block-title"><header><div><small>CUSTOMER ACCESS</small><h2 id="block-title">Block customer</h2></div><button className="icon-action" aria-label="Close" onClick={()=>setOpen(false)}><X/></button></header><div className="editor-form"><p className="is-wide">Customer: <strong>{customer.name}</strong><br/><small>{customer.email??customer.phone??"Guest customer"}</small></p><label className="is-wide">Reason<select value={reason} onChange={event=>setReason(event.target.value)}><option value="SPAM">Spam</option><option value="ABUSIVE_BEHAVIOUR">Abusive behaviour</option><option value="FRAUDULENT_ORDERS">Fraudulent orders</option><option value="REPEATED_FAKE_ORDERS">Repeated fake orders</option><option value="PAYMENT_ISSUE">Payment issue</option><option value="OTHER">Other</option></select></label><label className="is-wide">Internal note (optional)<textarea maxLength={1000} value={note} onChange={event=>setNote(event.target.value)}/></label><label className="checkbox-field is-wide"><input type="checkbox" checked={preventOrders} onChange={event=>setPreventOrders(event.target.checked)}/><span>Prevent new orders</span></label><label className="checkbox-field is-wide"><input type="checkbox" checked={preventAccess} onChange={event=>setPreventAccess(event.target.checked)}/><span>Prevent storefront access while signed in</span></label></div><footer className="editor-footer"><button className="button button--outline" onClick={()=>setOpen(false)}>Cancel</button><button className="button button--danger" disabled={busy||(!preventOrders&&!preventAccess)} onClick={()=>void mutate(true)}>{busy?"Blocking…":"Block customer"}</button></footer></section></div>}</>
}
