"use client"
/* eslint-disable react-hooks/purity -- elapsed kitchen time is intentionally initialized from the wall clock */

import { motion } from "motion/react"
import { ChefHat,Clock3,Printer,RefreshCw } from "lucide-react"
import { useCallback,useEffect,useMemo,useState } from "react"
import { ReceiptDocument,type ReceiptData } from "@/components/receipt-document"
import { createClient } from "@/lib/supabase/client"

type Modifier={option_name:string;group_name:string};type Item={id:string;product_name:string;quantity:number;unit_price:number;order_item_modifiers:Modifier[]};type Order={id:string;order_number:string;token_number:number;channel:string;operational_order_type:string;status:"CONFIRMED"|"PREPARING";created_at:string;confirmed_at:string|null;preparing_at:string|null;order_notes:string|null;delivery_instructions:string|null;order_items:Item[]}
function elapsed(from:string,now:number){const minutes=Math.max(0,Math.floor((now-new Date(from).getTime())/60000));return `${minutes}m`}
export function KitchenBoard({businessId,branch,initialOrders,thresholds,printSettings,business}:{businessId:string;branch:{id:string;name:string};initialOrders:Order[];thresholds:{prep_warning_minutes:number;prep_late_minutes:number};printSettings:{receipt_width_mm:number;show_prices_on_kitchen_ticket:boolean;receipt_footer:string};business:{name:string;phone:string|null}}){const [orders,setOrders]=useState(initialOrders);const [now,setNow]=useState(Date.now());const [busy,setBusy]=useState("");const [error,setError]=useState("");const [connection,setConnection]=useState<"live"|"polling">("polling");const [print,setPrint]=useState<ReceiptData|null>(null)
  const load=useCallback(async()=>{const {data}=await createClient().from("orders").select("id,order_number,token_number,channel,operational_order_type,status,created_at,confirmed_at,preparing_at,order_notes,delivery_instructions,order_items(id,product_name,quantity,unit_price,order_item_modifiers(option_name,group_name))").eq("business_id",businessId).eq("branch_id",branch.id).in("status",["CONFIRMED","PREPARING"]).order("created_at");if(data)setOrders(data as Order[])},[branch.id,businessId])
  useEffect(()=>{const clock=window.setInterval(()=>{if(document.visibilityState==="visible")setNow(Date.now())},10000);const poll=window.setInterval(()=>{if(document.visibilityState==="visible")void load()},15000);const supabase=createClient();const channel=supabase.channel(`kds-${branch.id}`).on("postgres_changes",{event:"*",schema:"public",table:"orders",filter:`branch_id=eq.${branch.id}`},()=>{if(document.visibilityState==="visible")void load()}).subscribe(status=>setConnection(status==="SUBSCRIBED"?"live":"polling"));return()=>{window.clearInterval(clock);window.clearInterval(poll);void supabase.removeChannel(channel)}},[branch.id,load])
  const columns=useMemo(()=>({CONFIRMED:orders.filter(order=>order.status==="CONFIRMED"),PREPARING:orders.filter(order=>order.status==="PREPARING")}),[orders]);const update=async(order:Order,status:"PREPARING"|"READY")=>{setBusy(order.id);const {error}=await createClient().from("orders").update({status}).eq("id",order.id);if(error)setError(error.message);else{setError("");await load()}setBusy("")}
  const printTicket=(order:Order)=>{setPrint({businessName:business.name,branchName:branch.name,phone:business.phone,orderNumber:order.order_number,tokenNumber:order.token_number,createdAt:order.created_at,orderType:order.operational_order_type,subtotal:0,discount:0,deliveryFee:0,tax:0,total:0,paymentMethod:"",paymentStatus:"",lines:order.order_items.map(item=>({name:item.product_name,quantity:item.quantity,unitPrice:item.unit_price,options:item.order_item_modifiers.map(mod=>`${mod.group_name}: ${mod.option_name}`),notes:order.order_notes??order.delivery_instructions??undefined})),footer:printSettings.receipt_footer,width:printSettings.receipt_width_mm===58?58:80,showPrices:printSettings.show_prices_on_kitchen_ticket,kind:"kitchen"});window.setTimeout(()=>window.print(),80)}
  return <div className="kds-page"><div className="page-heading no-print"><div><span className="eyebrow">KITCHEN DISPLAY · {branch.name}</span><h1>Live preparation board</h1><p>Elapsed times are calculated locally; workflow timestamps are persisted only when status changes.</p></div><div className={`connection-pill is-${connection}`}>{connection==="live"?"Realtime connected":"Polling fallback"}<button onClick={()=>void load()} aria-label="Refresh kitchen"><RefreshCw/></button></div></div>{error&&<div className="inline-notice is-error" role="alert">{error}</div>}<div className="kds-board no-print">{(["CONFIRMED","PREPARING"] as const).map(status=><section key={status}><header><span>{status==="CONFIRMED"?"Waiting":"Preparing"}</span><b>{columns[status].length}</b></header><div>{columns[status].map(order=>{const started=order.preparing_at??order.confirmed_at??order.created_at;const minutes=Math.max(0,Math.floor((now-new Date(started).getTime())/60000));const urgency=minutes>=thresholds.prep_late_minutes?"late":minutes>=thresholds.prep_warning_minutes?"warning":"normal";return <motion.article layout key={order.id} className={`kds-ticket is-${urgency}`} initial={{opacity:0,y:8}} animate={{opacity:1,y:0}} exit={{opacity:0,scale:.98}}><div className="kds-ticket__top"><span><small>TOKEN</small><strong>{String(order.token_number).padStart(3,"0")}</strong></span><span><Clock3/>{elapsed(started,now)}</span></div><div className="kds-ticket__meta"><b>{order.operational_order_type.replaceAll("_"," ")}</b><small>{order.order_number} · {order.channel}</small></div><div className="kds-ticket__items">{order.order_items.map(item=><div key={item.id}><strong>{item.quantity}× {item.product_name}</strong>{item.order_item_modifiers.map(mod=><small key={`${item.id}-${mod.option_name}`}>{mod.group_name}: {mod.option_name}</small>)}</div>)}</div>{(order.order_notes||order.delivery_instructions)&&<p className="kds-note">{order.order_notes??order.delivery_instructions}</p>}<footer><button className="button button--outline" onClick={()=>printTicket(order)}><Printer/>Ticket</button><button className="button" disabled={busy===order.id} onClick={()=>void update(order,status==="CONFIRMED"?"PREPARING":"READY")}>{status==="CONFIRMED"?"Start preparing":"Mark ready"}</button></footer></motion.article>})}{!columns[status].length&&<div className="kds-empty"><ChefHat/><strong>{status==="CONFIRMED"?"No waiting orders":"Kitchen is clear"}</strong></div>}</div></section>)}</div>{print&&<ReceiptDocument receipt={print}/>}</div>}
