"use client"

import { Coins, Crown, Gift, Save, Users, WalletCards, X } from "lucide-react"
import { useMemo, useState } from "react"
import { AppLoader } from "@italian-pizza/shared/app-loader"
import { createClient } from "@/lib/supabase/client"

export type LoyaltySettings={business_id:string;is_enabled:boolean;program_name:string;coin_name:string;coins_per_100_pkr:number;coin_value_pkr:number;start_earning_order:number;minimum_order_pkr:number;max_coins_per_order:number;loyal_order_threshold:number;vip_order_threshold:number;website_orders_only:boolean;show_earning_message:boolean;redemption_enabled:boolean;minimum_redeem_coins:number;max_redeem_percent:number}
type Wallet={customer_id:string;customer_name:string;email:string;balance_coins:number;lifetime_earned:number;completed_orders:number;tier:"MEMBER"|"LOYAL"|"VIP";last_earned_at:string|null}
export type LoyaltyDashboard={members:number;outstandingCoins:number;lifetimeIssued:number;loyalCustomers:number;vipCustomers:number;wallets:Wallet[]}

const numberFields:Array<keyof Pick<LoyaltySettings,"coins_per_100_pkr"|"coin_value_pkr"|"start_earning_order"|"minimum_order_pkr"|"max_coins_per_order"|"loyal_order_threshold"|"vip_order_threshold"|"minimum_redeem_coins"|"max_redeem_percent">>=["coins_per_100_pkr","coin_value_pkr","start_earning_order","minimum_order_pkr","max_coins_per_order","loyal_order_threshold","vip_order_threshold","minimum_redeem_coins","max_redeem_percent"]

export function LoyaltyManager({businessId,initialSettings,initialDashboard}:{businessId:string;initialSettings:LoyaltySettings;initialDashboard:LoyaltyDashboard}){
  const [settings,setSettings]=useState(initialSettings)
  const [dashboard,setDashboard]=useState(initialDashboard)
  const [query,setQuery]=useState("")
  const [busy,setBusy]=useState(false)
  const [message,setMessage]=useState("")
  const [adjusting,setAdjusting]=useState<Wallet|null>(null)
  const [adjustment,setAdjustment]=useState("")
  const [reason,setReason]=useState("")
  const sampleCoins=Math.min(settings.max_coins_per_order,Math.floor(1249/100)*settings.coins_per_100_pkr)
  const wallets=useMemo(()=>dashboard.wallets.filter(wallet=>`${wallet.customer_name} ${wallet.email} ${wallet.tier}`.toLowerCase().includes(query.toLowerCase())),[dashboard.wallets,query])
  const metrics=[{Icon:WalletCards,label:"Wallet members",value:dashboard.members},{Icon:Coins,label:"Outstanding coins",value:dashboard.outstandingCoins},{Icon:Gift,label:"Lifetime issued",value:dashboard.lifetimeIssued},{Icon:Users,label:"Loyal customers",value:dashboard.loyalCustomers},{Icon:Crown,label:"VIP customers",value:dashboard.vipCustomers}]
  const refresh=async()=>{const {data,error}=await createClient().rpc("loyalty_admin_dashboard",{p_business_id:businessId});if(error)throw error;setDashboard(data as LoyaltyDashboard)}
  const save=async()=>{setBusy(true);setMessage("");try{if(settings.vip_order_threshold<=settings.loyal_order_threshold)throw new Error("VIP threshold must be higher than Loyal threshold.");if(numberFields.some(field=>!Number.isInteger(Number(settings[field]))||Number(settings[field])<0)||settings.minimum_redeem_coins<1||settings.max_redeem_percent<1||settings.max_redeem_percent>100)throw new Error("Use valid whole numbers for reward settings.");const {error}=await createClient().from("loyalty_settings").update({...settings,updated_by:(await createClient().auth.getUser()).data.user?.id??null}).eq("business_id",businessId);if(error)throw error;setMessage(settings.is_enabled?"Loyalty settings saved and published to the website.":"Loyalty program paused and removed from the customer website.")}catch(error){const detail=error instanceof Error?error.message:"";setMessage(detail.startsWith("VIP threshold")||detail.startsWith("Use valid")?detail:"Unable to save loyalty settings. Please try again.")}finally{setBusy(false)}}
  const applyAdjustment=async()=>{if(!adjusting)return;setBusy(true);setMessage("");try{const coins=Number(adjustment);if(!Number.isInteger(coins)||coins===0)throw new Error("Enter a positive credit or negative debit amount.");const {error}=await createClient().rpc("adjust_customer_loyalty",{p_business_id:businessId,p_customer_id:adjusting.customer_id,p_coins:coins,p_note:reason.trim()});if(error)throw error;await refresh();setAdjusting(null);setAdjustment("");setReason("");setMessage("Customer wallet adjusted and audit logged.")}catch(error){const detail=error instanceof Error?error.message:"";setMessage(detail.startsWith("Enter a positive")||detail.includes("does not have enough coins")?detail:"Unable to adjust this wallet. Please try again.")}finally{setBusy(false)}}
  const setNumber=(field:typeof numberFields[number],value:string)=>setSettings(current=>({...current,[field]:Number(value)}))
  return <div className="loyalty-admin">
    <div className="page-heading"><div><span className="eyebrow">CUSTOMER RETENTION</span><h1>Loyalty & Wallet</h1><p>Reward genuine repeat customers only after delivered orders. Every coin is backed by an immutable order or audited adjustment.</p></div><button className="button" disabled={busy} onClick={()=>void save()}>{busy?<AppLoader active label="Saving loyalty settings"/>:<Save/>}{busy?"Saving…":"Save settings"}</button></div>
    {message&&<p className={`inline-notice ${message.startsWith("Unable")||message.startsWith("Enter")||message.startsWith("VIP")?"is-error":""}`} role="status">{message}</p>}
    <div className="loyalty-metrics">{metrics.map(({Icon,label,value})=><article key={label}><Icon/><span>{label}</span><strong>{Number(value).toLocaleString("en-PK")}</strong></article>)}</div>
    <div className="loyalty-admin-grid"><section className="panel loyalty-settings"><div className="panel-header"><div><h2>Reward rules</h2><p>Changes apply only to future delivered orders.</p></div><label className="loyalty-master-switch"><input type="checkbox" checked={settings.is_enabled} onChange={event=>setSettings(current=>({...current,is_enabled:event.target.checked}))}/><span>{settings.is_enabled?"Program active":"Program paused"}</span></label></div>
      <div className="loyalty-form-grid"><label>Program name<input value={settings.program_name} maxLength={80} onChange={event=>setSettings(current=>({...current,program_name:event.target.value}))}/></label><label>Coin display name<input value={settings.coin_name} maxLength={40} onChange={event=>setSettings(current=>({...current,coin_name:event.target.value}))}/></label><label>Coins per Rs 100 spent<input type="number" min="1" max="100" value={settings.coins_per_100_pkr} onChange={event=>setNumber("coins_per_100_pkr",event.target.value)}/><small>Calculated from item subtotal after discounts.</small></label><label>Value of one coin (PKR)<input type="number" min="1" max="100" value={settings.coin_value_pkr} onChange={event=>setNumber("coin_value_pkr",event.target.value)}/></label><label>Start earning from completed order #<input type="number" min="1" max="100" value={settings.start_earning_order} onChange={event=>setNumber("start_earning_order",event.target.value)}/><small>Set 2 to reward the customer starting with their second delivery.</small></label><label>Minimum eligible order (PKR)<input type="number" min="0" value={settings.minimum_order_pkr} onChange={event=>setNumber("minimum_order_pkr",event.target.value)}/></label><label>Maximum coins per order<input type="number" min="1" value={settings.max_coins_per_order} onChange={event=>setNumber("max_coins_per_order",event.target.value)}/></label><label>Loyal after completed orders<input type="number" min="1" value={settings.loyal_order_threshold} onChange={event=>setNumber("loyal_order_threshold",event.target.value)}/></label><label>VIP after completed orders<input type="number" min="2" value={settings.vip_order_threshold} onChange={event=>setNumber("vip_order_threshold",event.target.value)}/></label></div>
      <div className="loyalty-toggles"><label><input type="checkbox" checked={settings.website_orders_only} onChange={event=>setSettings(current=>({...current,website_orders_only:event.target.checked}))}/><span>Reward website orders only</span><small>Prevents anonymous counter/table sales from earning coins.</small></label><label><input type="checkbox" checked={settings.show_earning_message} onChange={event=>setSettings(current=>({...current,show_earning_message:event.target.checked}))}/><span>Show “You earned” message</span><small>Displayed once when the signed-in customer returns.</small></label><label><input type="checkbox" checked={settings.redemption_enabled} onChange={event=>setSettings(current=>({...current,redemption_enabled:event.target.checked}))}/><span>Allow coins at checkout</span><small>Signed-in customers can choose how many available coins to spend.</small></label></div>
      <div className="loyalty-form-grid"><label>Minimum coins per redemption<input type="number" min="1" max="100000" value={settings.minimum_redeem_coins} onChange={event=>setNumber("minimum_redeem_coins",event.target.value)}/><small>Customers may still choose 0 to save their coins.</small></label><label>Maximum item value covered (%)<input type="number" min="1" max="100" value={settings.max_redeem_percent} onChange={event=>setNumber("max_redeem_percent",event.target.value)}/><small>Set 100% to let customers use as many coins as their item total allows.</small></label></div>
      <div className="loyalty-rule-preview"><Coins/><span><small>EXAMPLE FOR RS 1,249 ELIGIBLE SPEND</small><strong>{sampleCoins} {settings.coin_name} = Rs {(sampleCoins*settings.coin_value_pkr).toLocaleString("en-PK")} wallet value</strong></span></div>
    </section>
    <section className="panel loyalty-explainer"><span className="eyebrow">HOW IT WORKS</span><h2>Earn, spend, stay protected</h2><ol><li><b>1</b><span>Customer orders using their account or verified email.</span></li><li><b>2</b><span>Nothing is awarded while received, preparing or cancelled.</span></li><li><b>3</b><span>On DELIVERED, the database credits that order exactly once.</span></li><li><b>4</b><span>At checkout, chosen coins are debited atomically; cancellation returns them automatically.</span></li></ol></section></div>
    <section className="panel section-gap"><div className="panel-header"><div><h2>Customer wallets</h2><p>Repeat-order classification and PKR-backed coin balances.</p></div><label className="search-field"><input aria-label="Search loyalty customers" placeholder="Search customer or tier" value={query} onChange={event=>setQuery(event.target.value)}/></label></div>{wallets.length?<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Customer</th><th>Tier</th><th>Delivered</th><th>Balance</th><th>Lifetime earned</th><th>Last earned</th><th>Action</th></tr></thead><tbody>{wallets.map(wallet=><tr key={wallet.customer_id}><td data-label="Customer"><strong>{wallet.customer_name}</strong><small>{wallet.email}</small></td><td data-label="Tier"><span className={`loyalty-tier tier-${wallet.tier.toLowerCase()}`}>{wallet.tier}</span></td><td data-label="Delivered">{wallet.completed_orders}</td><td data-label="Balance"><strong>{wallet.balance_coins} coins</strong><small>Rs {(wallet.balance_coins*settings.coin_value_pkr).toLocaleString("en-PK")}</small></td><td data-label="Lifetime">{wallet.lifetime_earned}</td><td data-label="Last earned">{wallet.last_earned_at?new Date(wallet.last_earned_at).toLocaleString("en-PK",{timeZone:"Asia/Karachi"}):"Not yet"}</td><td data-label="Action"><button className="button button--outline" onClick={()=>setAdjusting(wallet)}>Adjust</button></td></tr>)}</tbody></table></div>:<div className="empty-panel">Wallets appear after signed-in customers complete delivered orders.</div>}</section>
    {adjusting&&<div className="drawer-backdrop"><section className="editor loyalty-adjust" role="dialog" aria-modal="true" aria-labelledby="loyalty-adjust-title"><header><div><small>MANUAL WALLET ADJUSTMENT</small><h2 id="loyalty-adjust-title">{adjusting.customer_name}</h2></div><button className="icon-action" aria-label="Close adjustment" onClick={()=>setAdjusting(null)}><X/></button></header><div className="editor-form"><p className="is-wide">Current balance: <strong>{adjusting.balance_coins} {settings.coin_name}</strong>. Use a positive number to credit or a negative number to debit.</p><label>Coins<input type="number" value={adjustment} onChange={event=>setAdjustment(event.target.value)} placeholder="e.g. 10 or -5"/></label><label className="is-wide">Internal reason *<textarea value={reason} maxLength={240} onChange={event=>setReason(event.target.value)} placeholder="Customer service adjustment…"/></label></div><footer className="editor-footer"><button className="button button--outline" disabled={busy} onClick={()=>setAdjusting(null)}>Cancel</button><button className="button" disabled={busy||!reason.trim()||!adjustment} onClick={()=>void applyAdjustment()}>{busy?"Saving…":"Apply adjustment"}</button></footer></section></div>}
  </div>
}
