"use client"

import { AppLoader } from "@italian-pizza/shared/app-loader"
import { MOTION_DURATION, MOTION_EASE } from "@italian-pizza/shared/motion"
import { Bell, CheckCheck, ShoppingBag, TriangleAlert, X } from "lucide-react"
import Link from "next/link"
import { AnimatePresence, motion } from "motion/react"
import { useCallback, useEffect, useRef, useState } from "react"
import { useRouter } from "next/navigation"
import { createClient } from "@/lib/supabase/client"

type Notice={id:number;notification_type:string;title:string;message:string;entity_type:string|null;entity_id:string|null;is_read:boolean;created_at:string}
const relative=(value:string)=>{const seconds=Math.round((Date.parse(value)-Date.now())/1000);const absolute=Math.abs(seconds);const [amount,unit]:[number,Intl.RelativeTimeFormatUnit]=absolute<60?[seconds,"second"]:absolute<3600?[Math.round(seconds/60),"minute"]:absolute<86400?[Math.round(seconds/3600),"hour"]:[Math.round(seconds/86400),"day"];return new Intl.RelativeTimeFormat("en",{numeric:"auto"}).format(amount,unit)}

export function NotificationPopover({ businessId, unread, onUnread, revision=0 }: { businessId:string; unread:number; onUnread:(count:number)=>void;revision?:number }) {
  const router=useRouter();const [open,setOpen]=useState(false);const [loading,setLoading]=useState(false);const [rows,setRows]=useState<Notice[]>([]);const rootRef=useRef<HTMLDivElement>(null)
  const load=useCallback(async()=>{setLoading(true);const {data}=await createClient().from("notifications").select("id,notification_type,title,message,entity_type,entity_id,is_read,created_at").eq("business_id",businessId).is("resolved_at",null).order("is_read",{ascending:true}).order("created_at",{ascending:false}).limit(20);setRows((data??[]) as Notice[]);setLoading(false)},[businessId])
  useEffect(()=>{if(!open)return;const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load,open,revision])
  useEffect(()=>{if(!open)return;const close=(event:PointerEvent)=>{if(!rootRef.current?.contains(event.target as Node))setOpen(false)};const escape=(event:KeyboardEvent)=>{if(event.key==="Escape")setOpen(false)};document.addEventListener("pointerdown",close);document.addEventListener("keydown",escape);return()=>{document.removeEventListener("pointerdown",close);document.removeEventListener("keydown",escape)}},[open])
  async function markAll(){if(!unread)return;const {error}=await createClient().from("notifications").update({is_read:true,read_at:new Date().toISOString()}).eq("business_id",businessId).eq("is_read",false).is("resolved_at",null);if(!error){setRows(current=>current.map(row=>({...row,is_read:true})));onUnread(0)}}
  async function openNotice(row:Notice){if(!row.is_read){const {error}=await createClient().from("notifications").update({is_read:true,read_at:new Date().toISOString()}).eq("id",row.id).eq("business_id",businessId);if(!error)onUnread(Math.max(0,unread-1))}setOpen(false);if(row.entity_type==="orders"&&row.entity_id)router.push(`/orders?order=${encodeURIComponent(row.entity_id)}`);else router.push("/notifications")}
  return <div className="notification-popover-root" ref={rootRef}><button className="notification-button" type="button" aria-label={`${unread} unread notifications`} aria-haspopup="dialog" aria-expanded={open} onClick={()=>setOpen(value=>!value)}><Bell/>{unread>0&&<span>{unread>99?"99+":unread}</span>}</button><AnimatePresence>{open&&<motion.section className="notification-popover" role="dialog" aria-label="Recent notifications" initial={{opacity:0,y:-6,scale:.985}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:-4,scale:.99}} transition={{duration:MOTION_DURATION.page,ease:MOTION_EASE}}><header><div><strong>Active notifications</strong><small>{unread ? `${unread} unread` : "You're caught up"}</small></div><button type="button" className="icon-action notification-close" aria-label="Close notifications" onClick={()=>setOpen(false)}><X/></button>{unread>0&&<button type="button" className="notification-mark-all" onClick={()=>void markAll()}><CheckCheck/>Mark all read</button>}</header><div className="notification-popover__list">{loading?<div className="notification-loading"><AppLoader active label="Loading notifications"/>Loading notifications…</div>:rows.length?rows.map(row=>{const Icon=row.notification_type==="NEW_ORDER"?ShoppingBag:row.notification_type==="SYSTEM"?TriangleAlert:Bell;return <button type="button" key={row.id} className={row.is_read?"is-read":""} onClick={()=>void openNotice(row)}><i><Icon/></i><span><strong>{row.title}</strong><small>{row.message}</small><time>{relative(row.created_at)}</time></span>{!row.is_read&&<b aria-label="Unread"/>}</button>}):<div className="notification-empty"><Bell/><span>No active notifications.</span></div>}</div><footer><Link href="/notifications" onClick={()=>setOpen(false)}>View all notifications</Link></footer></motion.section>}</AnimatePresence></div>
}
