"use client"

import { useState } from "react"
import { Plus, Power } from "lucide-react"
import { createClient } from "@/lib/supabase/client"

type TableRow={id:string;code:string;name:string;seats:number;is_active:boolean}

export function TableManager({businessId,branchId,initialTables}:{businessId:string;branchId:string;initialTables:TableRow[]}){
  const [tables,setTables]=useState(initialTables),[name,setName]=useState(""),[code,setCode]=useState(""),[seats,setSeats]=useState("4"),[busy,setBusy]=useState(""),[message,setMessage]=useState("")
  const create=async(event:React.FormEvent)=>{event.preventDefault();setBusy("create");setMessage("");const {data,error}=await createClient().from("restaurant_tables").insert({business_id:businessId,branch_id:branchId,name:name.trim(),code:code.trim().toUpperCase(),seats:Number(seats)}).select("id,code,name,seats,is_active").single();if(error)setMessage(error.code==="23505"?"That table code already exists in this branch.":"Table could not be created.");else{setTables(rows=>[...rows,data].sort((a,b)=>a.name.localeCompare(b.name)));setName("");setCode("");setSeats("4");setMessage("Table created.")}setBusy("")}
  const toggle=async(table:TableRow)=>{setBusy(table.id);setMessage("");const {data,error}=await createClient().from("restaurant_tables").update({is_active:!table.is_active}).eq("id",table.id).eq("branch_id",branchId).select("id,code,name,seats,is_active").single();if(error)setMessage("Table status could not be changed. Close its active bill first if one exists.");else{setTables(rows=>rows.map(row=>row.id===data.id?data:row));setMessage(`${data.name} is now ${data.is_active?"active":"inactive"}.`)}setBusy("")}
  return <div className="page-stack"><div className="page-heading"><div><span className="eyebrow">DINE-IN CONTROL</span><h1>Restaurant tables</h1><p>Create stable table identities and prevent more than one open bill per table.</p></div></div>{message&&<p className="inline-notice" role="status">{message}</p>}<section className="panel"><div className="panel-header"><div><h2>Add a table</h2><p>Codes are unique inside this branch.</p></div></div><form className="form-grid" onSubmit={create}><label>Table name<input required maxLength={80} value={name} onChange={event=>setName(event.target.value)} placeholder="Table 7"/></label><label>Code<input required maxLength={40} value={code} onChange={event=>setCode(event.target.value)} placeholder="T07"/></label><label>Seats<input required type="number" min="1" max="100" value={seats} onChange={event=>setSeats(event.target.value)}/></label><button className="button" disabled={busy==="create"}><Plus/>Create table</button></form></section><section className="panel"><div className="panel-header"><div><h2>Branch floor</h2><p>Inactive tables cannot receive new waiter bills.</p></div></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Table</th><th>Code</th><th>Seats</th><th>Status</th><th>Action</th></tr></thead><tbody>{tables.map(table=><tr key={table.id}><td data-label="Table"><strong>{table.name}</strong></td><td data-label="Code">{table.code}</td><td data-label="Seats">{table.seats}</td><td data-label="Status"><span className={`status-badge ${table.is_active?"is-success":"is-warning"}`}>{table.is_active?"ACTIVE":"INACTIVE"}</span></td><td data-label="Action"><button className="button button--outline" disabled={busy===table.id} onClick={()=>void toggle(table)}><Power/>{table.is_active?"Deactivate":"Activate"}</button></td></tr>)}</tbody></table></div>{!tables.length&&<div className="empty-panel">No tables configured for this branch yet.</div>}</section></div>
}
