"use client"

import Image from "@/components/menu-image"
import { useRouter } from "next/navigation"
import { AnimatePresence, motion } from "motion/react"
import { CheckCircle2, Minus, Plus, Search, Send, ShoppingCart, Trash2, UtensilsCrossed, X } from "lucide-react"
import { useEffect, useMemo, useState } from "react"
import { formatPkr } from "@italian-pizza/shared"
import { AppLoader } from "@italian-pizza/shared/app-loader"
import { createClient } from "@/lib/supabase/client"

type Category={id:string;name:string}
type Option={image_url?:string|null;id:string;name:string;price_adjustment:number;is_default:boolean;is_active:boolean;sort_order:number}
type Group={id:string;name:string;selection_type:"SINGLE"|"MULTIPLE";is_required:boolean;min_selections:number;max_selections:number|null;modifier_options:Option[]}
type Assignment={product_id:string;sort_order:number;modifier_groups:Group|Group[]|null}
type RawProduct={id:string;name:string;sku?:string|null;category_id:string;base_price:number;sale_price:number|null;is_available:boolean;product_images:Array<{url:string;is_primary:boolean}>}
type Product=RawProduct&{price:number;groups:Group[];imageUrl:string|null}
type Deal={id:string;name:string;deal_price:number;image_url:string|null;starts_at:string|null;ends_at:string|null}
type Selection={groupId:string;optionId:string;label:string;price:number}
type CartLine={lineId:string;productId:string;itemKind:"product"|"deal";name:string;unitPrice:number;quantity:number;selections:Selection[];imageUrl:string|null}
type RecentOrder={id:string;order_number:string;token_number:number;table_reference:string;total:number;status:string;payment_status:string;created_at:string}
export type WaiterDashboard={todayOrders:number;activeOrders:number;completedOrders:number;todaySales:number;recentOrders:RecentOrder[]}

const productImage=(product:RawProduct)=>product.product_images?.find(item=>item.is_primary)?.url??product.product_images?.[0]?.url??null
const validDeal=(deal:Deal)=>{const now=Date.now();return(!deal.starts_at||new Date(deal.starts_at).getTime()<=now)&&(!deal.ends_at||new Date(deal.ends_at).getTime()>now)}

export function WaiterTerminal({businessId,waiterId,branch,logoUrl,categories,products:rawProducts,deals:rawDeals,assignments,initialDashboard}:{
  businessId:string;waiterId:string;branch:{id:string;name:string;city:string};logoUrl:string|null;categories:Category[];products:RawProduct[];deals:Deal[];assignments:Assignment[];initialDashboard:WaiterDashboard
}){
  const router=useRouter()
  const products=useMemo<Product[]>(()=>rawProducts.map(product=>({...product,price:Number(product.sale_price??product.base_price),imageUrl:productImage(product),groups:assignments.filter(item=>item.product_id===product.id).map(item=>Array.isArray(item.modifier_groups)?item.modifier_groups[0]:item.modifier_groups).filter((group):group is Group=>Boolean(group)).map(group=>({...group,modifier_options:(group.modifier_options??[]).filter(option=>option.is_active).sort((a,b)=>a.sort_order-b.sort_order)}))})),[assignments,rawProducts])
  const deals=useMemo(()=>rawDeals.filter(validDeal),[rawDeals])
  const [dashboard,setDashboard]=useState(initialDashboard)
  const [category,setCategory]=useState("all")
  const [query,setQuery]=useState("")
  const [cart,setCart]=useState<CartLine[]>([])
  const [editing,setEditing]=useState<Product|null>(null)
  const [selected,setSelected]=useState<Selection[]>([])
  const [tableReference,setTableReference]=useState("")
  const [guestName,setGuestName]=useState("")
  const [notes,setNotes]=useState("")
  const [busy,setBusy]=useState(false)
  const [message,setMessage]=useState("")
  const subtotal=cart.reduce((sum,line)=>sum+(line.unitPrice+line.selections.reduce((value,item)=>value+item.price,0))*line.quantity,0)
  const visible=products.filter(product=>(category==="all"||category==="deals"||product.category_id===category)&&`${product.name} ${product.sku??""}`.toLowerCase().includes(query.toLowerCase()))

  useEffect(()=>{const supabase=createClient();let timer:number|undefined;const refreshMenu=()=>{window.clearTimeout(timer);timer=window.setTimeout(()=>router.refresh(),250)};const refreshDashboard=async()=>{const {data}=await supabase.rpc("waiter_dashboard",{p_branch_id:branch.id});if(data)setDashboard(data as WaiterDashboard)};const channel=supabase.channel(`waiter-${waiterId}`).on("postgres_changes",{event:"*",schema:"public",table:"products",filter:`business_id=eq.${businessId}`},refreshMenu).on("postgres_changes",{event:"*",schema:"public",table:"deals",filter:`business_id=eq.${businessId}`},refreshMenu).on("postgres_changes",{event:"UPDATE",schema:"public",table:"orders",filter:`waiter_id=eq.${waiterId}`},()=>void refreshDashboard()).subscribe();return()=>{window.clearTimeout(timer);void supabase.removeChannel(channel)}},[branch.id,businessId,router,waiterId])

  const addLine=(line:Omit<CartLine,"lineId"|"quantity">)=>setCart(rows=>[...rows,{...line,lineId:crypto.randomUUID(),quantity:1}])
  const openProduct=(product:Product)=>{if(!product.groups.length){addLine({productId:product.id,itemKind:"product",name:product.name,unitPrice:product.price,selections:[],imageUrl:product.imageUrl});return}setEditing(product);setSelected(product.groups.flatMap(group=>group.modifier_options.filter(option=>option.is_default).slice(0,group.selection_type==="SINGLE"?1:undefined).map(option=>({groupId:group.id,optionId:option.id,label:`${group.name}: ${option.name}`,price:Number(option.price_adjustment)}))))}
  const toggle=(group:Group,option:Option)=>setSelected(current=>{const exists=current.some(item=>item.optionId===option.id);if(exists)return current.filter(item=>item.optionId!==option.id);const next=group.selection_type==="SINGLE"?current.filter(item=>item.groupId!==group.id):current;if(group.max_selections&&next.filter(item=>item.groupId===group.id).length>=group.max_selections)return current;return[...next,{groupId:group.id,optionId:option.id,label:`${group.name}: ${option.name}`,price:Number(option.price_adjustment)}]})
  const addCustomized=()=>{if(!editing)return;for(const group of editing.groups){if(selected.filter(item=>item.groupId===group.id).length<group.min_selections){setMessage(`Select ${group.name}.`);return}}addLine({productId:editing.id,itemKind:"product",name:editing.name,unitPrice:editing.price,selections:selected,imageUrl:editing.imageUrl});setEditing(null);setMessage("")}
  const quantity=(lineId:string,delta:number)=>setCart(rows=>rows.flatMap(line=>line.lineId!==lineId?[line]:line.quantity+delta<1?[]:[{...line,quantity:line.quantity+delta}]))
  const sendOrder=async()=>{if(!cart.length){setMessage("Add at least one item.");return}if(!tableReference.trim()){setMessage("Enter a table number or guest reference.");return}setBusy(true);setMessage("");const {data,error}=await createClient().rpc("create_waiter_pos_order",{p_payload:{branchId:branch.id,tableReference:tableReference.trim(),guestName:guestName.trim(),notes:notes.trim(),items:cart.map(line=>({itemKind:line.itemKind,productId:line.productId,quantity:line.quantity,modifiers:line.selections.map(item=>({groupId:item.groupId,optionId:item.optionId}))}))}});if(error){const safe=["restaurant is currently closed","selected product is unavailable","selected deal is unavailable","modifier selections are invalid","waiter access denied"];const detail=String(error.message??"").toLowerCase();setMessage(safe.find(item=>detail.includes(item))?error.message:"Unable to send this order. Refresh the menu and try again.");setBusy(false);return}const result=data as {id:string;orderNumber:string;tokenNumber:number;total:number;status:string;tableReference:string};const recent:RecentOrder={id:result.id,order_number:result.orderNumber,token_number:result.tokenNumber,table_reference:result.tableReference,total:result.total,status:result.status,payment_status:"UNPAID",created_at:new Date().toISOString()};setDashboard(current=>({...current,todayOrders:Number(current.todayOrders)+1,activeOrders:Number(current.activeOrders)+1,todaySales:Number(current.todaySales)+result.total,recentOrders:[recent,...current.recentOrders].slice(0,20)}));setCart([]);setTableReference("");setGuestName("");setNotes("");setMessage(`Order ${result.orderNumber} · Token ${String(result.tokenNumber).padStart(3,"0")} sent to POS and kitchen.`);setBusy(false)}

  return <div className="waiter-page">
    <header className="waiter-hero"><div className="waiter-identity">{logoUrl?<Image src={logoUrl} alt={`${branch.name} logo`} width={150} height={70} sizes="150px" unoptimized/>:<i><UtensilsCrossed/></i>}<span><small>WAITER TABLET</small><strong>{branch.name}</strong><em>{branch.city}</em></span></div><div className="waiter-stats"><div><span>Today</span><b>{dashboard.todayOrders}</b></div><div><span>Active</span><b>{dashboard.activeOrders}</b></div><div><span>Completed</span><b>{dashboard.completedOrders}</b></div><div><span>Order value</span><b>{formatPkr(Number(dashboard.todaySales))}</b></div></div></header>
    {message&&<p className={`inline-notice ${message.startsWith("Order ")?"":"is-error"}`} role="status">{message}</p>}
    <div className="waiter-layout"><section className="waiter-catalog"><label className="waiter-search"><Search/><input aria-label="Search menu" placeholder="Search products or SKU" value={query} onChange={event=>setQuery(event.target.value)}/></label><div className="waiter-categories"><button className={category==="all"?"is-active":""} onClick={()=>setCategory("all")}>All</button><button className={category==="deals"?"is-active":""} onClick={()=>setCategory("deals")}>Deals</button>{categories.map(item=><button key={item.id} className={category===item.id?"is-active":""} onClick={()=>setCategory(item.id)}>{item.name}</button>)}</div><div className="waiter-products">{(category==="all"||category==="deals")&&deals.filter(deal=>deal.name.toLowerCase().includes(query.toLowerCase())).map(deal=><button key={deal.id} onClick={()=>addLine({productId:deal.id,itemKind:"deal",name:deal.name,unitPrice:Number(deal.deal_price),selections:[],imageUrl:deal.image_url})}>{deal.image_url?<span className="waiter-product-image"><Image src={deal.image_url} alt="" fill sizes="(max-width: 700px) 46vw, 190px" unoptimized/></span>:<span className="waiter-product-image is-empty"><UtensilsCrossed/></span>}<small>DEAL</small><strong>{deal.name}</strong><b>{formatPkr(Number(deal.deal_price))}</b></button>)}{category!=="deals"&&visible.map(product=><button key={product.id} onClick={()=>openProduct(product)}>{product.imageUrl?<span className="waiter-product-image"><Image src={product.imageUrl} alt="" fill sizes="(max-width: 700px) 46vw, 190px" unoptimized/></span>:<span className="waiter-product-image is-empty"><UtensilsCrossed/></span>}<small>{categories.find(item=>item.id===product.category_id)?.name??"MENU"}</small><strong>{product.name}</strong><b>{formatPkr(product.price)}</b></button>)}</div>{!visible.length&&category!=="deals"&&!deals.length&&<div className="state-box">No matching available products.</div>}</section>
      <aside className="waiter-cart"><header><span><ShoppingCart/><strong>Current order</strong></span><b>{cart.reduce((sum,line)=>sum+line.quantity,0)} items</b></header><div className="waiter-cart-lines">{cart.map(line=><article key={line.lineId}><div>{line.imageUrl&&<span className="waiter-line-image"><Image src={line.imageUrl} alt="" fill sizes="52px" unoptimized/></span>}<span><strong>{line.name}</strong>{line.selections.map(item=><small key={item.optionId}>{item.label}</small>)}<b>{formatPkr((line.unitPrice+line.selections.reduce((sum,item)=>sum+item.price,0))*line.quantity)}</b></span></div><div className="waiter-quantity"><button aria-label={`Decrease ${line.name}`} onClick={()=>quantity(line.lineId,-1)}>{line.quantity===1?<Trash2/>:<Minus/>}</button><b>{line.quantity}</b><button aria-label={`Increase ${line.name}`} onClick={()=>quantity(line.lineId,1)}><Plus/></button></div></article>)}{!cart.length&&<div className="waiter-empty"><ShoppingCart/><p>Tap a product to start the table order.</p></div>}</div><div className="waiter-order-fields"><label>Table / guest reference *<input value={tableReference} maxLength={80} placeholder="Table 7" onChange={event=>setTableReference(event.target.value)}/></label><label>Guest name (optional)<input value={guestName} maxLength={120} placeholder="Guest name" onChange={event=>setGuestName(event.target.value)}/></label><label>Order notes<textarea value={notes} maxLength={500} placeholder="No onion, serve drinks first…" onChange={event=>setNotes(event.target.value)}/></label></div><footer><div><span>Total bill</span><strong>{formatPkr(subtotal)}</strong></div><button className="button" disabled={busy||!cart.length} onClick={()=>void sendOrder()}>{busy?<AppLoader active delay={0} label="Sending order"/>:<Send/>}{busy?"Sending…":"Send order"}</button><small>Prices and option totals are verified securely before the POS order is created.</small></footer></aside>
    </div>
    <section className="panel waiter-history"><div className="panel-header"><div><h2>My recent orders</h2><p>Live status and payment progress for orders sent from this tablet.</p></div></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Order</th><th>Table</th><th>Token</th><th>Total</th><th>Kitchen</th><th>Payment</th></tr></thead><tbody>{dashboard.recentOrders.map(order=><tr key={order.id}><td data-label="Order">{order.order_number}<small>{new Date(order.created_at).toLocaleString("en-PK",{timeZone:"Asia/Karachi"})}</small></td><td data-label="Table">{order.table_reference}</td><td data-label="Token">{String(order.token_number).padStart(3,"0")}</td><td data-label="Total">{formatPkr(Number(order.total))}</td><td data-label="Kitchen"><span className="status-badge">{order.status.replaceAll("_"," ")}</span></td><td data-label="Payment"><span className={`status-badge ${order.payment_status==="PAID"?"is-success":"is-warning"}`}>{order.payment_status}</span></td></tr>)}</tbody></table></div>{!dashboard.recentOrders.length&&<div className="empty-panel">No waiter orders yet.</div>}</section>
    <AnimatePresence>{editing&&<motion.div className="drawer-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}}><motion.section className="editor waiter-option-editor" role="dialog" aria-modal="true" aria-label={`Customize ${editing.name}`} initial={{y:40,opacity:0}} animate={{y:0,opacity:1}} exit={{y:30,opacity:0}}><header><div><small>CUSTOMIZE</small><h2>{editing.name}</h2></div><button className="icon-action" aria-label="Close options" onClick={()=>setEditing(null)}><X/></button></header><div className="modifier-groups">{editing.groups.map(group=><fieldset key={group.id}><legend>{group.name} {group.min_selections>0&&<small>Required</small>}</legend>{group.modifier_options.map(option=>{const active=selected.some(item=>item.optionId===option.id);return <button type="button" className={active?"is-selected":""} key={option.id} onClick={()=>toggle(group,option)}><span>{active?<CheckCircle2/>:<i/>}{option.image_url&&<Image className="addon-thumbnail" src={option.image_url} alt="" width={44} height={44} unoptimized/>}{option.name}</span><b>{option.price_adjustment?`+ ${formatPkr(Number(option.price_adjustment))}`:"Included"}</b></button>})}</fieldset>)}</div><footer className="editor-footer"><button className="button button--outline" onClick={()=>setEditing(null)}>Cancel</button><button className="button" onClick={addCustomized}>Add to current order</button></footer></motion.section></motion.div>}</AnimatePresence>
  </div>
}
