import Link from "next/link"
import { ExternalLink,FileText,Globe2,ImageUp,Send,Trash2,Users } from "lucide-react"
import { requirePlatformPermission } from "@/lib/auth"
import { createClient } from "@/lib/supabase/server"
import { PlatformShell } from "@/components/platform-shell"
import { MutationForm } from "@/components/mutation-form"
import { SubmitButton } from "@/components/submit-button"
import { EmptyState,PageHeader,StatusBadge } from "@/components/ui"
import { OnboardingFormBuilder } from "@/components/onboarding-form-builder"
import { CmsDocumentEditor } from "@/components/cms-document-editor"
import { formDefinitionSchema } from "@/lib/website-cms"
import { deleteTeamMemberAction,publishOnboardingFormAction,publishTeamMemberAction,saveTeamMemberAction,unpublishTeamMemberAction,uploadTeamImageAction } from "./actions"

type Row=Record<string,unknown>
const publicSite=process.env.QAZIPRO_PUBLIC_SITE_URL||"http://localhost:3003"
const statuses=["NEW","REVIEWING","NEEDS_INFO","APPROVED","REJECTED","CONVERTED"]

export default async function WebsiteCmsPage({searchParams}:{searchParams:Promise<{q?:string;status?:string}>}) {
  const filters=await searchParams
  const search=(filters.q??"").trim().toLowerCase()
  const selectedStatus=(filters.status??"").toUpperCase()
  const context=await requirePlatformPermission("website.manage")
  const client=await createClient()
  const [documents,team,form,submissions]=await Promise.all([
    client.from("platform_site_documents").select("*").order("key"),
    client.from("platform_site_team_members").select("*").order("display_order"),
    client.from("platform_onboarding_forms").select("*").eq("slug","client-onboarding").maybeSingle(),
    client.from("platform_onboarding_submissions").select("id,reference,client_data,selected_services,status,assigned_staff_user_id,created_at").order("created_at",{ascending:false}).limit(100),
  ])
  const definition=formDefinitionSchema.safeParse(form.data?.draft_definition)
  const dataError=[documents.error,team.error,form.error,submissions.error].find(Boolean)
  const filteredSubmissions=(submissions.data??[]).filter((row:Row)=>{
    const data=(row.client_data??{}) as Record<string,unknown>
    const haystack=[row.reference,data.restaurantName,data.contactName,data.email,data.phone].map(value=>String(value??"").toLowerCase()).join(" ")
    return (!search||haystack.includes(search))&&(!selectedStatus||String(row.status)===selectedStatus)
  })

  return <PlatformShell context={context}><PageHeader eyebrow="PUBLIC PLATFORM" title="QaziPro Website" description="Draft, preview and publish QaziPro.com content, the public team and signed client onboarding without a code deployment." actions={<a className="button" href={publicSite} target="_blank" rel="noreferrer">Open live website <ExternalLink/></a>}/>
    {dataError?<div className="data-notice">Website CMS migration is not available in this environment yet.</div>:null}
    <nav className="website-cms-tabs" aria-label="Website CMS sections"><a href="#content">Content</a><a href="#team">Team</a><a href="#form-builder">Form builder</a><a href="#submissions">Submissions</a></nav>
    <section className="panel" id="content"><header><div><p className="eyebrow">DRAFT → PREVIEW → PUBLISH</p><h2>Page content</h2></div><Globe2/></header><div className="cms-document-grid">{(documents.data??[]).map((row:Row)=><CmsDocumentEditor key={String(row.key)} documentKey={String(row.key)} label={String(row.label)} draftRevision={Number(row.draft_revision)} publishedVersion={Number(row.published_version)} published={Boolean(row.published_data)} content={row.draft_data as Record<string,unknown>} publicSite={publicSite}/>)}</div></section>
    <section className="panel" id="team"><header><div><p className="eyebrow">ABOUT / TEAM</p><h2>Public team manager</h2></div><Users/></header><p className="muted">Draft edits do not change the public website until each member is published.</p><details className="inline-create"><summary>Add team member</summary><TeamForm/></details><div className="team-manager-grid">{(team.data??[]).map((member:Row)=><article className="team-manager-card" key={String(member.id)}><header><div><strong>{String(member.name)}</strong><small>{String(member.title)}</small></div><StatusBadge value={member.published_snapshot?"PUBLISHED":"DRAFT"}/></header><details><summary>Edit profile</summary><TeamForm member={member}/></details><MutationForm action={uploadTeamImageAction} className="team-image-form"><input type="hidden" name="id" value={String(member.id)}/><label>Profile image<input type="file" name="image" accept="image/png,image/jpeg,image/webp" required/></label><SubmitButton className="button button-secondary"><ImageUp/> Upload</SubmitButton></MutationForm><div className="cms-actions"><MutationForm action={publishTeamMemberAction}><input type="hidden" name="id" value={String(member.id)}/><SubmitButton className="button">Publish profile</SubmitButton></MutationForm>{member.published_snapshot?<MutationForm action={unpublishTeamMemberAction} confirmation="Remove this team member from the public website? The draft will remain."><input type="hidden" name="id" value={String(member.id)}/><SubmitButton className="button button-danger">Unpublish</SubmitButton></MutationForm>:null}<MutationForm action={deleteTeamMemberAction} confirmation="Permanently delete this team member and stored profile image? This cannot be undone."><input type="hidden" name="id" value={String(member.id)}/><SubmitButton className="button button-danger"><Trash2/> Delete</SubmitButton></MutationForm></div></article>)}</div></section>
    <section className="panel form-builder-panel" id="form-builder"><header><div><p className="eyebrow">NO-CODE FORM</p><h2>Client onboarding builder</h2></div><FileText/></header>{form.data&&definition.success?<><div className="publish-strip"><span><StatusBadge value={Number(form.data.published_version)>0?"PUBLISHED":"DRAFT"}/> Draft r{String(form.data.draft_revision)} · Public v{String(form.data.published_version)}</span><MutationForm action={publishOnboardingFormAction} confirmation="Publish this complete form definition, services, packages and terms?"><input type="hidden" name="id" value={String(form.data.id)}/><SubmitButton className="button"><Send/> Publish form</SubmitButton></MutationForm></div><OnboardingFormBuilder id={String(form.data.id)} revision={Number(form.data.draft_revision)} definition={definition.data}/></>:<EmptyState title="No client form configured" detail="Apply the platform website CMS migration to create the safe default form."/>}</section>
    <section className="panel" id="submissions"><header><div><p className="eyebrow">SIGNED APPLICATIONS</p><h2>Client onboarding submissions</h2></div><FileText/></header><form className="cms-filter-form" action="/website#submissions"><label>Search<input name="q" defaultValue={filters.q} placeholder="Reference, restaurant, POC, email or phone"/></label><label>Status<select name="status" defaultValue={selectedStatus}><option value="">All statuses</option>{statuses.map(value=><option key={value}>{value}</option>)}</select></label><button className="button button-secondary" type="submit">Filter</button></form>{filteredSubmissions.length?<div className="table-wrap"><table><thead><tr><th>Reference</th><th>Restaurant / POC</th><th>Services</th><th>Status</th><th>Submitted</th><th/></tr></thead><tbody>{filteredSubmissions.map((row:Row)=>{const data=(row.client_data??{}) as Record<string,unknown>;const services=Array.isArray(row.selected_services)?row.selected_services as Row[]:[];return <tr key={String(row.id)}><td><strong>{String(row.reference)}</strong></td><td>{String(data.restaurantName??"—")}<small className="table-sub">{String(data.contactName??data.email??"")}</small></td><td>{services.map(item=>String(item.name)).join(", ")||"—"}</td><td><StatusBadge value={row.status}/></td><td>{new Date(String(row.created_at)).toLocaleString()}</td><td><Link className="text-link" href={`/website/submissions/${row.id}`}>Open</Link></td></tr>})}</tbody></table></div>:<EmptyState title="No matching onboarding submissions" detail="Adjust the search or status filter. New signed applications appear here automatically."/>}</section>
  </PlatformShell>
}

function TeamForm({member}:{member?:Row}){return <MutationForm action={saveTeamMemberAction} className="form-grid compact-form"><input type="hidden" name="id" value={member?String(member.id):""}/><label>Name<input name="name" required defaultValue={member?String(member.name):""}/></label><label>Role / title<input name="title" required defaultValue={member?String(member.title):""}/></label><label className="span-2">Short bio<textarea name="shortBio" rows={3} maxLength={700} defaultValue={member?String(member.short_bio??""):""}/></label><label className="span-2">Full bio<textarea name="fullBio" rows={4} maxLength={5000} defaultValue={member?String(member.full_bio??""):""}/></label><label>Email (optional)<input type="email" name="email" defaultValue={member?String(member.email??""):""}/></label><label>LinkedIn (optional)<input type="url" name="linkedin" defaultValue={member?String(member.linkedin_url??""):""}/></label><label>Other social<input type="url" name="social" defaultValue={member?String(member.social_url??""):""}/></label><label>Display order<input type="number" min="0" name="displayOrder" defaultValue={member?Number(member.display_order):0}/></label><label className="check-row"><input type="checkbox" name="featured" defaultChecked={Boolean(member?.featured)}/>Featured</label><label className="check-row"><input type="checkbox" name="active" defaultChecked={member?Boolean(member.active):true}/>Active</label><SubmitButton className="button span-2">Save team draft</SubmitButton></MutationForm>}
