import { MutationForm } from "@/components/mutation-form"
import { SubmitButton } from "@/components/submit-button"
import { ClipboardCheck } from "lucide-react"
import { createTaskAction, updateTaskStatusAction } from "@/app/actions"
import { OperationsTable } from "@/components/operations-table"
import { PlatformShell } from "@/components/platform-shell"
import { DataNotice, PageHeader, StatusBadge } from "@/components/ui"
import { requirePlatformStaff } from "@/lib/auth"
import { getModuleRows, getTaskOptions } from "@/lib/data"

type Row=Record<string,unknown>
const statuses=["OPEN","IN_PROGRESS","WAITING_CLIENT","WAITING_QAZIPRO","BLOCKED","RESOLVED","CLOSED"]
export default async function TasksPage({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) {
  const context=await requirePlatformStaff(),notice=await searchParams
  const [result,options]=await Promise.all([getModuleRows("tasks",Number(notice.page??1)),getTaskOptions()])
  return <PlatformShell context={context}><PageHeader eyebrow="TEAM OWNERSHIP" title="Operational tasks" description="Assign onboarding, support, deployment and billing work with a visible deadline and state."/>{result.error||options.error?<DataNotice message={result.error??options.error??"Data unavailable"}/>:null}{notice.created||notice.updated?<div className="success-banner">Task workflow updated and audited.</div>:null}{notice.error?<div className="form-error">Task action rejected safely ({notice.error}).</div>:null}<div className="workspace-grid"><section className="panel"><header><div><p className="eyebrow">ASSIGN WORK</p><h2>New task</h2></div><ClipboardCheck/></header><MutationForm action={createTaskAction} className="form-grid compact-form"><label className="span-2">Title<input name="title" required/></label><label>Restaurant<select name="businessId"><option value="">Platform-wide</option>{options.data.businesses.map((item)=><option key={String(item.id)} value={String(item.id)}>{String(item.name)}</option>)}</select></label><label>Owner<select name="assignedStaffUserId"><option value="">Unassigned</option>{options.data.staff.map((item)=><option key={String(item.user_id)} value={String(item.user_id)}>{String(item.display_name)}</option>)}</select></label><label>Team<select name="team">{["SALES","ONBOARDING","SUPPORT","DEVELOPMENT","DEPLOYMENT","BILLING","OPERATIONS"].map((value)=><option key={value}>{value}</option>)}</select></label><label>Priority<select name="priority"><option>LOW</option><option>NORMAL</option><option>HIGH</option><option>URGENT</option></select></label><label>Due at<input name="dueAt" type="datetime-local"/></label><label>Audit reason<input name="reason" required defaultValue="Operational work assignment"/></label><SubmitButton className="button span-2"><ClipboardCheck/>Create task</SubmitButton></MutationForm></section><section className="panel"><header><div><p className="eyebrow">WORK QUEUE</p><h2>Update status</h2></div></header><div className="record-list">{result.data.slice(0,12).map((row:Row)=><article className="record-row record-row-stack" key={String(row.id)}><div><strong>{String(row.title)}</strong><span>{String(row.team)} · <StatusBadge value={row.status}/></span></div><MutationForm action={updateTaskStatusAction} className="inline-action"><input name="taskId" type="hidden" value={String(row.id)}/><input name="reason" type="hidden" value="Task progress update"/><select name="status" defaultValue={String(row.status)}>{statuses.map((value)=><option key={value}>{value}</option>)}</select><SubmitButton className="button button-small">Update</SubmitButton></MutationForm></article>)}</div></section></div><OperationsTable rows={result.data} page={result.page} count={result.count} pageSize={result.pageSize} href="/tasks" columns={["title","businesses","team","priority","status","assigned_staff_user_id","due_at","created_at"]} empty="No tasks recorded"/></PlatformShell>
}
