import { deals, pizzaCrusts, pizzaExtras, pizzaSizes, products } from "@/data/demo-menu"
import { heroSlides } from "@/data/hero-slides"
import { menuSections } from "@/data/menu-sections"
import type { ProductModifierGroup, StorefrontSnapshot } from "@/types"

const pizzaGroups: ProductModifierGroup[] = [
  { id:"size", label:"Choose size", selection:"single", required:true, minSelections:1, maxSelections:1, options:pizzaSizes },
  { id:"crust", label:"Choose crust", selection:"single", required:true, minSelections:1, maxSelections:1, options:pizzaCrusts },
  { id:"extras", label:"Add extras", selection:"multiple", required:false, minSelections:0, maxSelections:4, options:pizzaExtras },
]

export const fallbackStorefront: StorefrontSnapshot = {
  source: "fallback",
  orderPersistence: "local-demo",
  business: {
    id: null,
    name: "Restaurant",
    displayName: "RESTAURANT",
    description: "Online ordering is temporarily unavailable.",
    footerDescription: "Online ordering is temporarily unavailable.",
    tagline: "Freshly made. Warmly delivered.",
    contactText: "Questions about an order? Our team is ready to help.",
    city: "",
    currency: "PKR",
    timezone: "Asia/Karachi",
    logoUrl: null,
    footerLogoUrl: null,
    faviconUrl: null,
    primaryColor: "#a92114",
    secondaryColor: "#e7a81a",
    websiteBackgroundColor: "#fbf7f2",
    headerBackgroundColor: "#ffffff",
    footerBackgroundColor: "#211d1b",
    productCardBackgroundColor: "#ffffff",
    textColor: "#211d1b",
    footerTextColor: "#f7f2ee",
    fontFamily: "Geist",
    fontStylesheetUrl: null,
    headerLogoSizePx: 56,
    footerLogoSizePx: 88,
    announcementEnabled: true,
    announcementText: "Free delivery up to 5 km · Additional distance may carry a delivery fee",
    reviewsEnabled: false,
    reviewsTitle: "Reviews",
    reviewsBusinessName: null,
    reviewsWidgetId: null,
    whatsappFloatingEnabled: false,
    whatsappNumber: "",
    whatsappLogoUrl: null,
    whatsappMessage: "Hello, I would like to place an order.",
    whatsappSide: "LEFT",
    whatsappSizePx: 58,
    whatsappBottomPx: 24,
    whatsappSideOffsetPx: 24,
    socialLinks: [],
    footerLinks: [],
    contentPages: [],
  },
  branch: {
    id: null,
    name: "Restaurant",
    restaurantName: "Restaurant",
    locationRevision: 1,
    city: "",
    countryCode: null,
    region: null,
    temporarilyClosed: false,
    isOpen: true,
    pickupEnabled: true,
    deliveryEnabled: true,
    freeDistanceKm: 5,
    extraKmRate: 100,
    originLatitude: null,
    originLongitude: null,
    todayHoursLabel: "Hours unavailable",
  },
  heroSlides,
  heroSettings: { autoplay: true, intervalMs: 5500, transitionMs: 650 },
  menuSections,
  products: products.map((product) => product.customizable ? { ...product, modifierGroups: pizzaGroups } : product),
  deals,
  deliveryAreas: [],
}
