do $test$
declare
  business uuid; branch uuid; other_branch uuid; actor uuid:=gen_random_uuid(); cashier uuid:=gen_random_uuid(); membership uuid;
  category uuid; product uuid:=gen_random_uuid(); table_id uuid:=gen_random_uuid(); other_table uuid:=gen_random_uuid(); area uuid:=gen_random_uuid();
  shift_id uuid; request jsonb; result jsonb; replay jsonb; denied boolean; first_order uuid; payment_count integer; tax_bps integer;
  ingredient uuid:=gen_random_uuid(); qr_table uuid:=gen_random_uuid(); qr_order uuid; table_token text; other_shift uuid; other_result jsonb;
begin
  select b.id,br.id into business,branch from public.businesses b join public.branches br on br.business_id=b.id where b.slug='italian-pizza' and br.is_active order by br.created_at limit 1;
  if business is null then raise exception 'Staging restaurant fixture is unavailable'; end if;
  insert into auth.users(id,email,raw_app_meta_data,raw_user_meta_data) values(actor,'pos-rollback-'||actor||'@example.test','{}','{}'),(cashier,'pos-rollback-'||cashier||'@example.test','{}','{}');
  insert into public.staff_memberships(business_id,branch_id,user_id,role,is_active) values(business,branch,actor,'OWNER',true);
  insert into public.staff_memberships(business_id,branch_id,user_id,role,is_active,permissions_customized) values(business,branch,cashier,'CASHIER',true,true) returning id into membership;
  insert into public.staff_membership_branches(membership_id,business_id,branch_id) values(membership,business,branch);
  insert into public.staff_membership_permissions(membership_id,permission_code) values(membership,'pos.use'),(membership,'customers.read');
  perform set_config('request.jwt.claim.sub',actor::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
  update public.branches set temporarily_closed=false,pickup_enabled=true,delivery_enabled=true where id=branch;
  update public.business_hours set is_closed=false,opens_at='00:00',closes_at='23:59:59' where branch_id=branch;
  select id into category from public.categories where business_id=business limit 1;
  insert into public.products(id,business_id,category_id,name,slug,base_price,is_active,is_available) values(product,business,category,'POS rollback fixture','pos-rollback-'||product,1000,true,true);
  insert into public.ingredients(id,business_id,branch_id,name,unit,current_stock) values(ingredient,business,branch,'POS rollback ingredient '||ingredient,'piece',20);
  insert into public.recipes(business_id,product_id,ingredient_id,quantity) values(business,product,ingredient,1);
  insert into public.branches(business_id,name,code,address,city) values(business,'POS rollback second branch','PX'||substr(actor::text,1,8),'Fixture only','Fixture') returning id into other_branch;
  insert into public.restaurant_tables(id,business_id,branch_id,code,name) values(table_id,business,branch,'PX'||substr(actor::text,1,8),'POS rollback table'),(other_table,business,other_branch,'PX2'||substr(actor::text,1,8),'Other branch table');
  select (public.open_pos_shift(branch,0)).id into shift_id;
  select coalesce(tax_rate_bps,0) into tax_bps from public.business_operating_settings where business_id=business;
  request:=jsonb_build_object('branchId',branch,'shiftId',shift_id,'clientReference',gen_random_uuid(),'orderType','TAKEAWAY','cashReceived',5000,'paymentMethodCode','CASH','items',jsonb_build_array(jsonb_build_object('productId',product,'quantity',1,'modifiers','[]'::jsonb)));
  result:=public.create_pos_order(request); first_order:=(result->>'id')::uuid;
  if (result->>'total')::integer<>1000+round(1000*coalesce(tax_bps,0)/10000.0)::integer then raise exception 'Tax pricing mismatch'; end if;
  replay:=public.create_pos_order(request);
  if replay->>'id'<>result->>'id' or not (replay->>'idempotent')::boolean then raise exception 'Replay created another sale'; end if;
  select count(*) into payment_count from public.payment_transactions where order_id=first_order;
  if payment_count<>1 then raise exception 'Duplicate payment'; end if;
  denied:=false;begin perform public.create_pos_order(request||jsonb_build_object('cashReceived',9000));exception when sqlstate '22023' then denied:=true;end;if not denied then raise exception 'Changed replay accepted';end if;
  denied:=false;begin perform public.create_pos_order(request||jsonb_build_object('clientReference',gen_random_uuid(),'expectedTotal',1));exception when sqlstate '22023' then denied:=true;end;if not denied then raise exception 'Stale price accepted';end if;
  denied:=false;begin perform public.create_pos_order(request||jsonb_build_object('clientReference',gen_random_uuid(),'cashReceived',1));exception when sqlstate '22023' then denied:=true;end;if not denied then raise exception 'Insufficient cash accepted';end if;
  denied:=false;begin perform public.create_pos_order(request||jsonb_build_object('clientReference',gen_random_uuid(),'paymentMethodCode','NOT_CONFIGURED'));exception when sqlstate '22023' then denied:=true;end;if not denied then raise exception 'Unconfigured tender accepted';end if;
  result:=public.create_pos_order(request||jsonb_build_object('clientReference',gen_random_uuid(),'orderType','PICKUP'));
  if not exists(select 1 from public.orders where id=(result->>'id')::uuid and operational_order_type='PICKUP' and branch_id=branch and business_id=business and payment_status='PAID') then raise exception 'Pickup mapping failed';end if;
  denied:=false;begin perform public.create_pos_order(request||jsonb_build_object('clientReference',gen_random_uuid(),'orderType','DINE_IN','tableId',other_table));exception when sqlstate '22023' then denied:=true;end;if not denied then raise exception 'Cross-branch table accepted';end if;
  result:=public.create_pos_order(request||jsonb_build_object('clientReference',gen_random_uuid(),'orderType','DINE_IN','tableId',table_id));
  if not exists(select 1 from public.restaurant_table_sessions where order_id=(result->>'id')::uuid and source='WAITER') then raise exception 'Dine-in mapping failed';end if;
  insert into public.restaurant_tables(id,business_id,branch_id,code,name) values(qr_table,business,branch,'QX'||substr(actor::text,1,8),'POS QR rollback') returning public_token into table_token;
  replay:=public.create_order_authoritative(jsonb_build_object('channel','WEBSITE','branchId',branch,'serviceMode','DINE_IN','tableToken',table_token,'idempotencyKey',gen_random_uuid(),'customerName','QR rollback','customerPhone','Counter','items',request->'items'),null);
  qr_order:=(replay->>'id')::uuid;
  replay:=public.settle_waiter_pos_order(qr_order,shift_id,5000);
  replay:=public.settle_waiter_pos_order(qr_order,shift_id,5000);
  if not (replay->>'idempotent')::boolean or (select count(*) from public.payment_transactions where order_id=qr_order)<>1 then raise exception 'QR payment retry duplicated';end if;
  if not exists(select 1 from public.orders where id=qr_order and channel='WEBSITE' and service_mode='DINE_IN' and branch_id=branch and payment_status='PAID') then raise exception 'QR POS mapping failed';end if;
  insert into public.delivery_areas(id,branch_id,slug,name) values(area,branch,'pos-rollback-'||area,'POS rollback area');
  insert into public.delivery_rules(branch_id,free_distance_km,extra_km_rate,maximum_distance_km) values(branch,5,100,8) on conflict(branch_id) do update set free_distance_km=5,extra_km_rate=100,maximum_distance_km=8;
  replay:=public.create_pos_order(request||jsonb_build_object('clientReference',gen_random_uuid(),'orderType','DELIVERY','customerName','Delivery rollback','customerPhone','Counter','deliveryAreaId',area,'deliveryAddress','Rollback address','distanceKm',6));
  if (select delivery_fee from public.orders where id=(replay->>'id')::uuid)<>100 then raise exception 'Delivery fee mismatch';end if;
  denied:=false;begin perform public.create_pos_order(request||jsonb_build_object('clientReference',gen_random_uuid(),'orderType','DELIVERY','customerName','Delivery rollback','customerPhone','Counter','deliveryAreaId',area,'deliveryAddress','Rollback address','distanceKm',9));exception when sqlstate '22023' then denied:=true;end;if not denied then raise exception 'Out of range delivery accepted';end if;
  insert into public.pos_payment_methods(business_id,code,name,kind,requires_reference,is_active) values(business,'QA_CARD','Rollback manual card','CARD',true,true);
  replay:=public.create_pos_order(request||jsonb_build_object('clientReference',gen_random_uuid(),'paymentMethodCode','QA_CARD','paymentReference','POS-ROLLBACK-MANUAL'));
  if (select count(*) from public.payment_transactions where order_id=(replay->>'id')::uuid and payment_method='QA_CARD')<>1 then raise exception 'Configured manual payment failed';end if;
  select (public.open_pos_shift(other_branch,0)).id into other_shift;
  other_result:=public.create_pos_order(request||jsonb_build_object('clientReference',gen_random_uuid(),'branchId',other_branch,'shiftId',other_shift,'customerName','Other branch only','customerPhone','POS-OTHER-BRANCH'));
  perform set_config('request.jwt.claim.sub',cashier::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',cashier,'role','authenticated')::text,true);
  denied:=false;begin perform public.create_pos_order(request);exception when sqlstate '22023' or sqlstate '42501' then denied:=true;end;if not denied then raise exception 'Other cashier replay accepted';end if;
  denied:=false;begin perform public.cancel_pos_order(first_order,'Unauthorized rollback test');exception when sqlstate '42501' then denied:=true;end;if not denied then raise exception 'Unauthorized refund accepted';end if;
  denied:=false;begin perform public.create_pos_order(request||jsonb_build_object('clientReference',gen_random_uuid(),'promoCode','ANY'));exception when sqlstate '42501' then denied:=true;end;if not denied then raise exception 'Unauthorized discount accepted';end if;
  denied:=false;begin perform public.create_pos_order(request||jsonb_build_object('clientReference',gen_random_uuid(),'branchId',other_branch));exception when sqlstate '42501' then denied:=true;end;if not denied then raise exception 'Wrong branch accepted';end if;
  replay:=public.customer_directory(business,0,'POS-OTHER-BRANCH');
  if (replay->>'total')::integer<>0 then raise exception 'Customer directory leaks branch';end if;
  perform set_config('request.jwt.claim.sub',actor::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',actor,'role','authenticated')::text,true);
  perform public.set_pos_order_stage(first_order,'PREPARING');perform public.set_pos_order_stage(first_order,'READY');perform public.set_pos_order_stage(first_order,'DELIVERED');
  if (select current_stock from public.ingredients where id=ingredient)<>19 then raise exception 'Canonical delivered-order stock consumption failed';end if;
  if (select count(*) from public.inventory_consumptions where order_id=first_order)<>1 then raise exception 'Inventory consumption duplicated';end if;
  result:=public.cancel_pos_order((result->>'id')::uuid,'Authorized rollback test');
  replay:=request||jsonb_build_object('clientReference',gen_random_uuid());
  result:=public.create_pos_order(replay);
  perform public.cancel_pos_order((result->>'id')::uuid,'Replay reversal protection');
  denied:=false;begin perform public.create_pos_order(replay);exception when sqlstate '22023' then denied:=true;end;if not denied then raise exception 'Reversed sale represented as paid';end if;
  insert into public.service_entitlements(business_id,capability_key,source,enabled) values(business,'pos.web','OVERRIDE',false) on conflict(business_id,capability_key,source) do update set enabled=false;
  denied:=false;begin perform public.create_pos_order(request||jsonb_build_object('clientReference',gen_random_uuid()));exception when sqlstate '42501' then denied:=true;end;if not denied then raise exception 'Disabled entitlement accepted';end if;
  update public.service_entitlements set enabled=true where business_id=business and capability_key='pos.web' and source='OVERRIDE';
  update public.businesses set is_active=false where id=business;
  denied:=false;begin perform public.create_pos_order(request||jsonb_build_object('clientReference',gen_random_uuid()));exception when sqlstate '42501' then denied:=true;end;if not denied then raise exception 'Inactive business accepted';end if;
  update public.businesses set is_active=true where id=business;
  perform set_config('request.jwt.claim.sub',cashier::text,true);
  perform set_config('request.jwt.claims',jsonb_build_object('sub',cashier,'role','authenticated')::text,true);
  perform set_config('pos.test.other_order',other_result->>'id',true);perform set_config('pos.test.own_order',first_order::text,true);perform set_config('pos.test.business',business::text,true);perform set_config('pos.test.branch',branch::text,true);
end;
$test$;
set local role authenticated;
do $rls$
begin
  if exists(select 1 from public.orders where id=current_setting('pos.test.other_order')::uuid) then raise exception 'Orders RLS leaks another branch';end if;
  if not exists(select 1 from public.orders where id=current_setting('pos.test.own_order')::uuid) then raise exception 'Orders RLS hides authorized branch (scope %, permission %)',public.staff_can_access_branch(current_setting('pos.test.business')::uuid,current_setting('pos.test.branch')::uuid),public.has_permission(current_setting('pos.test.business')::uuid,'orders.read');end if;
  if not exists(select 1 from public.order_items where order_id=current_setting('pos.test.own_order')::uuid) then raise exception 'POS-only cashier cannot read receipt items';end if;
  if not exists(select 1 from public.restaurant_tables where branch_id=current_setting('pos.test.branch')::uuid) then raise exception 'POS-only cashier cannot read branch tables';end if;
end;
$rls$;
reset role;
select 'POS_DATABASE_CHECKS_PASSED' as result;
