import { MutationForm } from "@/components/mutation-form"
import { SubmitButton } from "@/components/submit-button"
import { Activity, Siren } from "lucide-react"
import { createIncidentAction } from "@/app/actions"
import { OperationsTable } from "@/components/operations-table"
import { PlatformShell } from "@/components/platform-shell"
import { DataNotice, PageHeader } from "@/components/ui"
import { requirePlatformStaff } from "@/lib/auth"
import { getModuleRows, getPlatformBusinessOptions } from "@/lib/data"

export default async function HealthPage({ searchParams }: { searchParams: Promise<{ created?: string; error?: string; page?: string }> }) {
  const context = await requirePlatformStaff(), notice = await searchParams
  const [result, businesses] = await Promise.all([getModuleRows("health",Number(notice.page??1)), getPlatformBusinessOptions()])
  return <PlatformShell context={context}><PageHeader eyebrow="ATTENTION CENTER" title="System health and incidents" description="Monitoring that is not connected remains Unknown. Open incidents only from real evidence."/>{result.error || businesses.error ? <DataNotice message={result.error ?? businesses.error ?? "Data unavailable"}/> : null}{notice.created ? <div className="success-banner">Incident opened, assigned and audited.</div> : null}{notice.error ? <div className="form-error">Incident action was rejected safely ({notice.error}).</div> : null}<div className="workspace-grid"><section className="panel"><header><div><p className="eyebrow">OPEN INCIDENT</p><h2>Record verified signal</h2></div><Siren/></header><MutationForm action={createIncidentAction} className="form-grid compact-form"><label className="span-2">Restaurant (optional)<select name="businessId"><option value="">Platform-wide</option>{businesses.data.map((item) => <option value={String(item.id)} key={String(item.id)}>{String(item.name)}</option>)}</select></label><label>Severity<select name="severity"><option>INFO</option><option>WARNING</option><option>CRITICAL</option></select></label><label>Environment<select name="environment"><option>STAGING</option><option>PRODUCTION</option><option>LOCAL</option></select></label><label>Component<input name="component" required placeholder="API / DNS / POS sync"/></label><label>Correlation ID<input name="requestId"/></label><label className="span-2">Title<input name="title" required/></label><label className="span-2">Human-readable summary<textarea name="summary" required rows={3}/></label><label className="span-2">Technical detail<textarea name="technicalDetails" rows={3}/></label><label className="span-2">Audit reason<input name="reason" required defaultValue="Verified operational signal"/></label><SubmitButton className="button span-2"><Activity/>Open incident</SubmitButton></MutationForm></section><section className="panel"><header><div><p className="eyebrow">HEALTH POLICY</p><h2>Signal rules</h2></div></header><p className="muted">No provider status is inferred. Missing Sentry, Vercel, DNS, push-worker or database probes stay Unknown until a trusted adapter reports evidence.</p></section></div><OperationsTable rows={result.data} page={result.page} count={result.count} pageSize={result.pageSize} href="/health" columns={["title","businesses","component","environment","severity","health_state","status","last_seen_at"]} empty="No incident records"/></PlatformShell>
}
