import Link from "next/link"
import { formatPkr } from "@italian-pizza/shared"
import { CustomerRestrictionAction } from "@/components/customer-restriction-action"
import { requirePermission } from "@/lib/auth"
import { createClient } from "@/lib/supabase/server"

type Customer={customer_key:string;customer_id:string|null;name:string;email:string|null;phone:string|null;order_count:number;spend:number;average_order:number;last_order:string|null;first_order:string|null;account_created:string|null;last_sign_in:string|null;provider:string|null;address_count:number;favourite_count:number;restriction_status:"ACTIVE"|"BLOCKED";favourites:Array<{productId:string;name:string}>}
export default async function Page({searchParams}:{searchParams:Promise<{page?:string;q?:string;customer?:string}>}){
  const context=await requirePermission("customers.read");const params=await searchParams;const page=Math.max(0,Math.min(100000,Number(params.page)||0));const query=(params.q??"").slice(0,100);const supabase=await createClient()
  const result=await supabase.rpc("customer_directory",{p_business_id:context.businessId,p_offset:page*50,p_query:query})
  const directory=(result.data??{total:0,rows:[]}) as {total:number;rows:Customer[]};const selected=directory.rows.find(row=>row.customer_key===params.customer);const canManage=context.role==="OWNER"||context.permissions.includes("customers.manage")
  let history:Array<{id:string;order_number:string;total:number;status:string;created_at:string}>=[]
  if(selected){const {data}=selected.customer_id?await supabase.rpc("customer_order_history",{p_business_id:context.businessId,p_customer_id:selected.customer_id}):await supabase.rpc("customer_order_history",{p_business_id:context.businessId,p_phone:selected.phone});history=data??[]}
  return <><div className="page-heading"><div><h1>Customers</h1><p>Account, order activity and customer access controls.</p></div></div><form className="resource-toolbar"><label className="search-field"><input name="q" defaultValue={query} placeholder="Name, phone or email" aria-label="Search customers"/></label><button className="button">Search</button><span>{directory.total} customers</span></form>
    {result.error?<div className="inline-notice is-error" role="alert">Customer records could not be loaded.</div>:directory.rows.length?<div className="data-table-wrap"><table className="data-table"><thead><tr><th>Name</th><th>Email / provider</th><th>Phone</th><th>Orders</th><th>Lifetime / avg</th><th>Last sign-in</th><th>Saved / favourites</th><th>Status</th><th>Actions</th></tr></thead><tbody>{directory.rows.map(row=><tr key={row.customer_key}><td data-label="Name">{row.name}</td><td data-label="Email">{row.email??"Guest"}{row.provider&&<small>{row.provider}</small>}</td><td data-label="Phone">{row.phone??"—"}</td><td data-label="Orders">{row.order_count}</td><td data-label="Lifetime / avg">{formatPkr(row.spend)}<small>{formatPkr(row.average_order)} avg</small></td><td data-label="Last sign-in">{row.last_sign_in?new Date(row.last_sign_in).toLocaleString("en-PK",{timeZone:"Asia/Karachi"}):"—"}</td><td data-label="Saved / favourites">{row.address_count} / {row.favourite_count}</td><td data-label="Status"><span className={`status-badge ${row.restriction_status==="BLOCKED"?"is-danger":"is-success"}`}>{row.restriction_status}</span></td><td data-label="Actions"><div className="table-actions"><Link className="button button--outline" href={`/customers?page=${page}&q=${encodeURIComponent(query)}&customer=${encodeURIComponent(row.customer_key)}`}>View</Link><CustomerRestrictionAction businessId={context.businessId} customer={row} canManage={canManage}/></div></td></tr>)}</tbody></table></div>:<div className="state-box">No matching customers.</div>}
    <div className="heading-actions section-gap">{page>0&&<Link className="button button--outline" href={`/customers?page=${page-1}&q=${encodeURIComponent(query)}`}>Previous</Link>}<span>Page {page+1}</span>{(page+1)*50<directory.total&&<Link className="button button--outline" href={`/customers?page=${page+1}&q=${encodeURIComponent(query)}`}>Next</Link>}</div>
    {selected&&<section className="panel section-gap"><div className="panel-header"><div><h2>{selected.name}</h2><small>{selected.email??"Guest customer"} · {selected.provider??"Guest"}</small></div><span className={`status-badge ${selected.restriction_status==="BLOCKED"?"is-danger":"is-success"}`}>{selected.restriction_status}</span></div>{selected.favourites.length>0&&<p><strong>Favourites:</strong> {selected.favourites.map(item=>item.name).join(", ")}</p>}{history.map(order=><div className="order-line" key={order.id}><span>{order.order_number}<small>{order.status}</small></span><strong>{formatPkr(order.total)}</strong></div>)}</section>}
  </>
}
