import Image from "next/image"
import Link from "next/link"
import { ArrowUpRight,CircleCheck,Compass,HeartHandshake,Layers3 } from "lucide-react"
import { pageMetadata } from "@/lib/metadata"
import { getPublishedDocument,getPublishedTeam } from "@/lib/platform-cms"
export const metadata=pageMetadata("About QaziPro","Meet the people and product thinking behind QaziPro's connected restaurant systems.","/about")
export const revalidate=60
export default async function About() {
  const [content,team]=await Promise.all([getPublishedDocument("about",{eyebrow:"ABOUT QAZIPRO",title:"Software should serve the people using it.",story:"QaziPro is focused on connected restaurant operations, modern commerce and dependable digital products.",mission:"Turn complicated work into a clear, dependable experience.",vision:"",teamHeading:"People responsible for the platform.",ctaLabel:"Talk to QaziPro",ctaHref:"/contact"}),getPublishedTeam()])
  const ctaHref=["/contact","/book-a-demo","/client-onboarding","/restaurant-platform"].includes(String(content.ctaHref))?String(content.ctaHref):"/contact"
  return <><section className="page-hero founder-hero"><div className="container founder-hero-grid"><div><span className="eyebrow">{String(content.eyebrow)}</span><h1>{String(content.title)}</h1><p>{String(content.story)}</p><p>{String(content.mission)}</p>{content.vision?<p>{String(content.vision)}</p>:null}<Link className="button button-primary" href={ctaHref}>{String(content.ctaLabel||"Talk to QaziPro")} <ArrowUpRight size={18}/></Link></div><figure className="founder-portrait founder-portrait-primary"><Image src="/founder/qazi-raheel-ahmad-studio.webp" width={1080} height={1438} sizes="(max-width: 900px) 100vw, 42vw" alt="Qazi Raheel Ahmad, founder of QaziPro" priority/><figcaption><strong>Qazi Raheel Ahmad</strong><span>Founder · QaziPro</span></figcaption></figure></div></section>
    <section className="content-section"><div className="container"><div className="section-heading"><span className="eyebrow">OUR POINT OF VIEW</span><h2>Clarity before complexity.</h2><p>Good software gives teams a reliable source of truth and gives the business room to adapt.</p></div><div className="content-grid"><article className="content-card"><Compass/><h3>Start with the work</h3><p>Understand the daily operation before drawing the interface.</p></article><article className="content-card"><Layers3/><h3>Connect the pieces</h3><p>Design across systems so information does not get stranded.</p></article><article className="content-card"><HeartHandshake/><h3>Stay accountable</h3><p>Build carefully, test honestly and be clear about what is ready.</p></article></div></div></section>
    <section className="content-section founder-story"><div className="container founder-story-grid"><figure className="founder-portrait founder-portrait-secondary"><Image src="/founder/qazi-raheel-ahmad-profile.webp" width={1080} height={1280} sizes="(max-width: 720px) 100vw, 38vw" alt="Portrait of Qazi Raheel Ahmad"/></figure><div><span className="eyebrow">FOUNDER&apos;S NOTE</span><h2>Build the system around the business—not the other way around.</h2><p className="text-muted">QaziPro works with restaurants and growing businesses that want thoughtful technology without unnecessary complexity.</p><ul className="check-list"><li><CircleCheck/> Connected restaurant systems</li><li><CircleCheck/> Purpose-built commerce experiences</li><li><CircleCheck/> Dependable custom web products</li></ul></div></div></section>
    <section className="content-section team-section"><div className="container"><div className="section-heading"><span className="eyebrow">THE QAZIPRO TEAM</span><h2>{String(content.teamHeading||"People responsible for the platform.")}</h2><p>Only profiles published by QaziPro Platform Owners appear here.</p></div>{team.length?<div className="public-team-grid">{team.map(member=><article className="public-team-card" key={String(member.id)}>{member.imagePath?<Image src={`/api/team-image/${member.id}`} alt={`${String(member.name)} — ${String(member.title)}`} width={700} height={700} sizes="(max-width: 680px) 100vw, 33vw"/>:<div className="team-image-fallback" aria-hidden="true">{String(member.name).slice(0,1)}</div>}<div><span>{String(member.title)}</span><h3>{String(member.name)}</h3><p>{String(member.shortBio||"")}</p>{member.linkedinUrl?<a className="text-link" href={String(member.linkedinUrl)} target="_blank" rel="noreferrer">LinkedIn <ArrowUpRight size={15}/></a>:null}</div></article>)}</div>:<div className="empty-proof"><h3>Team profiles are being prepared.</h3><p>QaziPro publishes verified team information only—no placeholder people.</p></div>}</div></section></>
}
