import { PackagePlus } from "lucide-react"
import { createServicePackageAction } from "@/app/actions"
import { PlatformShell } from "@/components/platform-shell"
import { DataNotice, EmptyState, PageHeader, StatusBadge } from "@/components/ui"
import { requirePlatformStaff } from "@/lib/auth"
import { getModuleRows } from "@/lib/data"

const capabilities = ["admin.restaurant","pos.web","pos.desktop","inventory","kitchen","waiter","rider","website.ordering","loyalty","reports.advanced","mobile.android","mobile.ios"]

export default async function PackagesPage({ searchParams }: { searchParams: Promise<{ created?:string; error?:string; page?:string }> }) {
  const notice=await searchParams
  const context=await requirePlatformStaff(),result=await getModuleRows("packages",Number(notice.page??1))
  return <PlatformShell context={context}><PageHeader eyebrow="COMMERCIAL CONTROL" title="Service packages" description="Package defaults and explicit capabilities—no competitor pricing or hidden frontend-only flags."/>{result.error?<DataNotice message={result.error}/>:null}{notice.created?<div className="success-banner">Package created and audited.</div>:null}{notice.error?<div className="form-error">Package creation was rejected. Check the unique code and values.</div>:null}<div className="workspace-grid"><section className="panel"><header><div><p className="eyebrow">ACTIVE CATALOG</p><h2>Configured packages</h2></div></header>{result.data.length?<div className="record-list">{result.data.map((row)=><div className="record-row" key={String(row.id)}><div><strong>{String(row.name)} · {String(row.code)}</strong><small>{String(row.currency)} {Number(row.base_fee??0).toLocaleString()} / {String(row.billing_frequency).toLowerCase()} · {String(row.included_branches)} branches included</small></div><StatusBadge value={row.is_active?"ACTIVE":"INACTIVE"}/></div>)}</div>:<EmptyState title="No packages configured" detail="Create a package before provisioning the first restaurant."/>}</section><section className="panel"><header><div><p className="eyebrow">NEW PACKAGE</p><h2>Commercial template</h2></div><PackagePlus/></header><form action={createServicePackageAction} className="form-grid compact-form"><label>Package code<input name="code" required pattern="[A-Z][A-Z0-9_]*" placeholder="GROWTH"/></label><label>Display name<input name="name" required placeholder="Growth"/></label><label>Currency<input name="currency" defaultValue="PKR" maxLength={3}/></label><label>Billing<select name="billingFrequency"><option>MONTHLY</option><option>QUARTERLY</option><option>ANNUAL</option><option>CUSTOM</option></select></label><label>Base fee<input name="baseFee" type="number" min="0" defaultValue="0"/></label><label>Setup fee<input name="setupFee" type="number" min="0" defaultValue="0"/></label><label>Included branches<input name="includedBranches" type="number" min="1" defaultValue="1"/></label><label>Extra branch fee<input name="additionalBranchFee" type="number" min="0" defaultValue="0"/></label><label>Terminal fee<input name="terminalFee" type="number" min="0" defaultValue="0"/></label><label className="span-2">Description<textarea name="description" rows={2}/></label><fieldset className="span-2 capability-fieldset"><legend>Default entitlements</legend>{capabilities.map((value)=><label key={value}><input type="checkbox" name="capabilities" value={value}/>{value}</label>)}</fieldset><label className="span-2">Reason<input name="reason" required defaultValue="Initial package configuration"/></label><button className="button span-2">Create package</button></form></section></div></PlatformShell>
}
