/* eslint-disable @next/next/no-img-element */
import Link from "next/link"
import type { ReactNode } from "react"
import { notFound } from "next/navigation"
import { Activity, AppWindow, ArrowLeft, Building2, ExternalLink, Globe2, Headphones, MonitorSmartphone, Network, ReceiptText, ShieldCheck, Users } from "lucide-react"
import { addBranchAction, resendRestaurantOwnerInvitationAction, setBranchStatusAction, setEntitlementAction, setRestaurantOwnerInvitationStatusAction, transitionRestaurantAction, updateBranchAction, updateRestaurantAction } from "@/app/actions"
import { BranchLocationFields } from "@/components/branch-location-fields"
import { PlatformShell } from "@/components/platform-shell"
import { DataNotice, EmptyState, PageHeader, StatusBadge } from "@/components/ui"
import { requirePlatformStaff } from "@/lib/auth"
import { getRestaurant } from "@/lib/data"
import { supportedServices } from "@/lib/onboarding"
import { canTransitionRestaurant, type RestaurantLifecycle } from "@/lib/platform"

type Row = Record<string, unknown>
const rows = (value: unknown) => Array.isArray(value) ? value as Row[] : value ? [value as Row] : []
const lifecycleValues: RestaurantLifecycle[] = ["LEAD", "AGREEMENT_PENDING", "ONBOARDING", "CONFIGURATION", "STAGING", "CLIENT_REVIEW", "READY", "ACTIVE", "SUSPENDED", "OFFBOARDING", "ARCHIVED"]

export default async function RestaurantWorkspace({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<Record<string, string | undefined>> }) {
  const context = await requirePlatformStaff()
  const { id } = await params
  const notice = await searchParams
  const result = await getRestaurant(id)
  if (!result.data && !result.error) notFound()
  if (!result.data) return <PlatformShell context={context}><DataNotice message={result.error ?? "Restaurant unavailable"}/></PlatformShell>

  const { business, onboarding, subscription, entitlements, apps, domains, deployments, incidents, tickets, devices, audit, invitations, memberships } = result.data
  const branding = rows(business.business_branding)[0]
  const branches = rows(business.branches)
  const lifecycle = String(onboarding?.lifecycle ?? "LEAD") as RestaurantLifecycle
  const packageValue = rows(subscription?.service_packages)[0]
  const transitions = lifecycleValues.filter((value) => canTransitionRestaurant(lifecycle, value))
  const entitlementMap = new Map<string, Row>()
  for (const item of entitlements) {
    const capability = String(item.capability_key)
    if (!entitlementMap.has(capability) || item.source === "OVERRIDE") entitlementMap.set(capability, item)
  }
  const returnTo = `/restaurants/${id}`

  return <PlatformShell context={context}>
    <Link className="back-link" href="/restaurants"><ArrowLeft/>Restaurant directory</Link>
    <PageHeader eyebrow="RESTAURANT 360°" title={String(branding?.display_name ?? business.name)} description={`${business.slug} · ${business.city} · Tenant ${business.id}`} actions={<><StatusBadge value={lifecycle}/><StatusBadge value={business.is_active ? "ACTIVE" : "INACTIVE"}/></>}/>
    {result.error ? <DataNotice message={result.error}/> : null}
    {notice.created ? <div className="success-banner">Restaurant provisioned once. It remains inactive until its lifecycle reaches Active.</div> : null}
    {notice.updated || notice.profile || notice.entitlement || notice.branchStatus ? <div className="success-banner">Change saved and audited.</div> : null}
    {notice.branch ? <div className="success-banner">Branch saved. Delivery remains disabled until location and delivery rules are verified.</div> : null}
    {notice.invite ? <div className="success-banner">{notice.invite === "suppressed" ? "Synthetic QA invitation safely recorded without external email delivery." : "Owner invitation state updated and audited."}</div> : null}
    {notice.delivery === "pending" ? <div className="attention-banner">Delivery was requested but remains pending because the branch has no verified delivery rule or complete coordinates.</div> : null}
    {notice.error ? <div className="form-error">The operation was rejected safely ({notice.error}).</div> : null}

    <nav className="workspace-tabs"><a href="#overview">Overview</a><a href="#access">Owner & access</a><a href="#branches">Branches</a><a href="#services">Services & billing</a><a href="#website">Domains</a><a href="#apps">Apps</a><a href="#health">Health</a><a href="#audit">Audit</a></nav>

    <section id="overview" className="workspace-hero"><div className="workspace-identity"><div className="restaurant-mark">{branding?.logo_url ? <img src={String(branding.logo_url)} alt=""/> : <Building2/>}</div><div><p className="eyebrow">CLIENT WORKSPACE</p><h2>{String(business.name)}</h2><p>{String(business.email ?? "No email")} · {String(business.phone ?? "No phone")}</p></div></div><div className="workspace-summary"><Summary label="Package" value={packageValue?.name ?? "Unassigned"}/><Summary label="Branches" value={branches.length}/><Summary label="Currency" value={business.currency}/><Summary label="Timezone" value={business.timezone}/></div></section>

    <div className="workspace-grid">
      <section className="panel lifecycle-panel"><header><div><p className="eyebrow">LIFECYCLE GATE</p><h2>Activation and archive</h2></div><StatusBadge value={lifecycle}/></header><p>Deactivate by moving an active restaurant to Suspended. Archive is a final soft-delete state that preserves tenant data and audit history; permanent hard delete is intentionally unavailable.</p>{transitions.length ? <form action={transitionRestaurantAction} className="transition-form"><input type="hidden" name="businessId" value={id}/><label>Next valid state<select name="lifecycle">{transitions.map((value) => <option key={value}>{value}</option>)}</select></label><label>Reason<input name="reason" required minLength={3} placeholder="Client approval / operational reason"/></label><button className="button">Apply transition</button></form> : <p className="muted">Archived records cannot transition further.</p>}</section>
      <section className="panel"><header><div><p className="eyebrow">EDIT RESTAURANT</p><h2>Business profile</h2></div><Building2/></header>{context.permissions.includes("restaurants.edit") ? <details className="inline-create"><summary>Edit business and owner details</summary><form action={updateRestaurantAction} className="form-grid"><input type="hidden" name="businessId" value={id}/><label>Restaurant name<input name="name" required defaultValue={String(business.name ?? "")}/></label><label>Display name<input name="displayName" defaultValue={String(branding?.display_name ?? business.name ?? "")}/></label><label>Owner name<input name="ownerName" required defaultValue={String(onboarding?.owner_name ?? "")}/></label><label>Owner email<input name="ownerEmail" required type="email" defaultValue={String(onboarding?.owner_email ?? business.email ?? "")}/></label><label>Owner phone<input name="ownerPhone" defaultValue={String(onboarding?.owner_phone ?? "")}/></label><label>Business phone<input name="phone" defaultValue={String(business.phone ?? "")}/></label><label>City<input name="city" required defaultValue={String(business.city ?? "")}/></label><label>Currency<input name="currency" required maxLength={3} defaultValue={String(business.currency ?? "PKR")}/></label><label>Timezone<input name="timezone" required defaultValue={String(business.timezone ?? "Asia/Karachi")}/></label><label className="span-2">Address<textarea name="address" rows={2} defaultValue={String(business.address ?? "")}/></label><label className="span-2">Commercial notes<textarea name="commercialNotes" rows={2} defaultValue={String(onboarding?.commercial_notes ?? "")}/></label><label className="span-2">Audit reason<input name="reason" required defaultValue="Approved restaurant profile update"/></label><button className="button span-2">Save restaurant</button></form></details> : <p className="muted">Read-only access.</p>}</section>
    </div>

    <WorkspaceSection id="access" eyebrow="OWNER & ACCESS" title="Invitation and membership state" icon={<Users/>}>
      <dl className="definition-list"><dt>Owner</dt><dd>{String(onboarding?.owner_name ?? "Not recorded")}</dd><dt>Email</dt><dd>{String(onboarding?.owner_email ?? business.email ?? "Not recorded")}</dd><dt>Phone</dt><dd>{String(onboarding?.owner_phone ?? business.phone ?? "Not recorded")}</dd><dt>Assigned QaziPro staff</dt><dd>{String(onboarding?.assigned_staff_user_id ?? "Unassigned")}</dd></dl>
      <div className="access-grid"><RecordPanel title="Invitations" rows={invitations} empty="No invitation record"/><RecordPanel title="Active memberships" rows={memberships} empty="Owner has not accepted the invitation yet"/></div>
      {context.permissions.includes("restaurants.edit") ? invitations.filter((invitation) => invitation.role === "OWNER" && invitation.status === "PENDING").map((invitation) => <div className="entity-actions" key={String(invitation.id)}><span><strong>{String(invitation.email)}</strong><small> Pending owner invitation</small></span><form action={resendRestaurantOwnerInvitationAction}><input type="hidden" name="businessId" value={id}/><input type="hidden" name="invitationId" value={String(invitation.id)}/><input type="hidden" name="reason" value="Restaurant 360 owner invitation resend"/><button className="button button-small button-secondary" disabled={!invitation.is_active}>Resend invitation</button></form><form action={setRestaurantOwnerInvitationStatusAction}><input type="hidden" name="businessId" value={id}/><input type="hidden" name="invitationId" value={String(invitation.id)}/><input type="hidden" name="active" value={invitation.is_active ? "false" : "true"}/><input type="hidden" name="reason" value="Restaurant 360 pending owner access control"/><button className={`button button-small ${invitation.is_active ? "button-danger" : "button-secondary"}`}>{invitation.is_active ? "Deactivate invitation" : "Activate invitation"}</button></form></div>) : null}
      <p className="form-help">Passwords are never visible or stored here. Restaurant roles and branch scope remain canonical in staff memberships; login alone never grants Super Admin access.</p>
    </WorkspaceSection>

    <WorkspaceSection id="branches" eyebrow="LOCATION OPERATIONS" title="Branches" icon={<Network/>}>
      {branches.length ? <div className="branch-management-list">{branches.map((branch) => <article className="entity-card branch-management-card" key={String(branch.id)}><header><div><h3>{String(branch.name)}</h3><p>{String(branch.city)} · {String(branch.code)}</p></div><StatusBadge value={branch.is_active ? "ACTIVE" : "INACTIVE"}/></header><dl><dt>Address</dt><dd>{String(branch.formatted_address ?? branch.address ?? "Not set")}</dd><dt>Coordinates</dt><dd>{branch.latitude && branch.longitude ? `${branch.latitude}, ${branch.longitude}` : "Pending"}</dd><dt>Pickup</dt><dd>{branch.pickup_enabled ? "Enabled" : "Disabled"}</dd><dt>Delivery</dt><dd>{branch.delivery_enabled ? "Enabled" : "Pending / disabled"}</dd></dl>
        {context.permissions.includes("branches.manage") ? <div className="entity-actions"><details><summary>Edit branch</summary><form action={updateBranchAction} className="form-grid"><input type="hidden" name="businessId" value={id}/><input type="hidden" name="branchId" value={String(branch.id)}/><label>Branch name<input name="name" required defaultValue={String(branch.name ?? "")}/></label><label>Code<input name="code" required defaultValue={String(branch.code ?? "")}/></label><BranchLocationFields initial={{ phone: String(branch.phone ?? ""), address: String(branch.formatted_address ?? branch.address ?? ""), city: String(branch.city ?? ""), region: String(branch.region ?? ""), countryCode: String(branch.country_code ?? "PK"), countryName: String(branch.country_name ?? ""), postalCode: String(branch.postal_code ?? ""), latitude: branch.latitude == null ? null : Number(branch.latitude), longitude: branch.longitude == null ? null : Number(branch.longitude), locationProvider: String(branch.location_provider ?? ""), providerPlaceId: String(branch.provider_place_id ?? ""), locationName: String(branch.location_name ?? "") }}/><label>Timezone<input name="timezone" required defaultValue={String(branch.timezone ?? business.timezone ?? "Asia/Karachi")}/></label><label className="check-row"><input type="checkbox" name="pickupEnabled" defaultChecked={Boolean(branch.pickup_enabled)}/>Pickup</label><label className="check-row"><input type="checkbox" name="deliveryEnabled" defaultChecked={Boolean(branch.delivery_enabled)}/>Delivery</label><label className="span-2">Audit reason<input name="reason" required defaultValue="Approved branch update"/></label><button className="button span-2">Save branch</button></form></details><form action={setBranchStatusAction}><input type="hidden" name="returnTo" value={returnTo}/><input type="hidden" name="businessId" value={id}/><input type="hidden" name="branchId" value={String(branch.id)}/><input type="hidden" name="active" value={branch.is_active ? "false" : "true"}/><input type="hidden" name="reason" value="Restaurant 360 branch lifecycle control"/><button className={`button button-small ${branch.is_active ? "button-danger" : "button-secondary"}`}>{branch.is_active ? "Deactivate" : "Activate"}</button></form></div> : null}
      </article>)}</div> : <EmptyState title="No branches" detail="A restaurant requires at least one active branch before activation."/>}
      {context.permissions.includes("branches.manage") ? <details className="inline-create"><summary>Add branch</summary><form action={addBranchAction} className="form-grid"><input type="hidden" name="returnTo" value={returnTo}/><input type="hidden" name="businessId" value={id}/><label>Branch name<input name="name" required/></label><label>Code<input name="code" required/></label><BranchLocationFields initial={{ city: String(business.city ?? ""), countryCode: "PK" }}/><label>Timezone<input name="timezone" required defaultValue={String(business.timezone ?? "Asia/Karachi")}/></label><label className="check-row"><input type="checkbox" name="pickupEnabled" defaultChecked/>Pickup</label><label className="check-row"><input type="checkbox" name="deliveryEnabled"/>Request delivery</label><label className="span-2">Reason<input name="reason" required defaultValue="New client branch"/></label><p className="form-help span-2">Delivery stays pending until the existing delivery rule and coordinates are verified.</p><button className="button span-2">Create branch safely</button></form></details> : null}
    </WorkspaceSection>

    <WorkspaceSection id="services" eyebrow="CAPABILITY CONTROL" title="Services, package and billing" icon={<ShieldCheck/>}>
      <div className="split-content"><dl className="definition-list"><dt>Package</dt><dd>{String(packageValue?.name ?? "Unassigned")}</dd><dt>Subscription</dt><dd><StatusBadge value={subscription?.status ?? "MISSING"}/></dd><dt>Base fee</dt><dd>{String(subscription?.currency ?? business.currency)} {Number(subscription?.base_fee ?? 0).toLocaleString()}</dd><dt>Setup fee</dt><dd>{String(subscription?.currency ?? business.currency)} {Number(subscription?.setup_fee ?? 0).toLocaleString()}</dd><dt>Next invoice</dt><dd>{String(subscription?.next_invoice_date ?? "Not scheduled")}</dd><dt>Manage</dt><dd><Link className="text-link" href="/billing">Open billing</Link></dd></dl><div className="entitlement-list">{supportedServices.map(([capability, label]) => { const item = entitlementMap.get(capability); const enabled = Boolean(item?.enabled); return <div key={capability}><span>{label}<small>{item ? String(item.source) : "not configured"}</small></span>{context.permissions.includes("subscriptions.manage") ? <form action={setEntitlementAction}><input type="hidden" name="returnTo" value={returnTo}/><input type="hidden" name="businessId" value={id}/><input type="hidden" name="capability" value={capability}/><input type="hidden" name="enabled" value={enabled ? "false" : "true"}/><input type="hidden" name="reason" value="Restaurant 360 service override"/><button className={`button button-small ${enabled ? "button-danger" : "button-secondary"}`}>{enabled ? "Disable" : "Enable"}</button></form> : <StatusBadge value={enabled ? "ENABLED" : "DISABLED"}/>}</div> })}</div></div>
    </WorkspaceSection>

    <WorkspaceSection id="website" eyebrow="CUSTOMER EXPERIENCE" title="Domains" icon={<Globe2/>}>{domains.length ? <div className="card-grid">{domains.map((domain) => <article className="entity-card" key={String(domain.id)}><header><div><h3>{String(domain.hostname)}</h3><p>{String(domain.purpose)}</p></div><StatusBadge value={domain.verification_status}/></header><dl><dt>DNS</dt><dd><StatusBadge value={domain.dns_status}/></dd><dt>SSL</dt><dd><StatusBadge value={domain.ssl_status}/></dd><dt>Auth callback</dt><dd><StatusBadge value={domain.auth_redirect_ready ? "READY" : "PENDING"}/></dd><dt>Last check</dt><dd>{String(domain.last_checked_at ?? "Never")}</dd></dl></article>)}</div> : <EmptyState title="No domains configured" detail="Add a domain from Domains. It stays pending until real DNS, SSL and tenant resolution checks pass."/>}</WorkspaceSection>
    <WorkspaceSection id="apps" eyebrow="WHITE-LABEL RELEASES" title="Android and iOS apps" icon={<AppWindow/>}><div className="card-grid">{apps.map((app) => <article className="entity-card" key={String(app.platform)}><header><div><h3>{String(app.platform)}</h3><p>{String(app.app_name ?? "App name pending")}</p></div><StatusBadge value={app.release_status}/></header><dl><dt>Identifier</dt><dd className="mono">{String(app.application_identifier ?? "Not configured")}</dd><dt>Credentials</dt><dd><StatusBadge value={app.credential_status}/></dd><dt>Push</dt><dd><StatusBadge value={app.push_status}/></dd><dt>Version</dt><dd>{String(app.version_name ?? "—")} ({String(app.build_number ?? "—")})</dd></dl>{app.store_url ? <a className="text-link" href={String(app.store_url)} target="_blank" rel="noreferrer">Open store<ExternalLink/></a> : null}</article>)}</div><p className="form-help">Signing and store publishing are intentionally outside onboarding. Configure records from Apps; no deployment success is fabricated.</p></WorkspaceSection>

    <WorkspaceSection id="health" eyebrow="DEPLOYMENT & HEALTH" title="Known operational evidence" icon={<Activity/>}><div className="dashboard-grid"><RecordPanel title="Deployments" rows={deployments} empty="No deployment evidence recorded"/><RecordPanel title="Incidents" rows={incidents} empty="No incidents recorded"/></div></WorkspaceSection>
    <WorkspaceSection id="pos" eyebrow="TERMINAL FLEET" title="Desktop POS devices" icon={<MonitorSmartphone/>}>{devices.length ? <div className="table-wrap"><table><thead><tr><th>Device</th><th>Branch</th><th>Version</th><th>Last sync</th><th>Status</th></tr></thead><tbody>{devices.map((device) => <tr key={String(device.id)}><td className="mono">{String(device.name ?? device.id)}</td><td className="mono">{String(device.branch_id)}</td><td>{String(device.app_version ?? "Unknown")}</td><td>{String(device.last_sync_at ?? "Never")}</td><td><StatusBadge value={device.is_active ? "ACTIVE" : "DISABLED"}/></td></tr>)}</tbody></table></div> : <EmptyState title="No POS devices registered" detail="A device appears after an authorized branch downloads its offline catalog."/>}</WorkspaceSection>
    <WorkspaceSection id="support" eyebrow="CLIENT CARE" title="Support" icon={<Headphones/>}><RecordPanel title="Support tickets" rows={tickets} empty="No support tickets recorded"/></WorkspaceSection>
    <WorkspaceSection id="audit" eyebrow="IMMUTABLE HISTORY" title="Activity and audit" icon={<ReceiptText/>}><RecordPanel title="Sensitive actions" rows={audit} empty="No platform audit events recorded"/></WorkspaceSection>
  </PlatformShell>
}

function Summary({ label, value }: { label: string; value: unknown }) { return <span><small>{label}</small><strong>{String(value ?? "—")}</strong></span> }
function WorkspaceSection({ id, eyebrow, title, icon, children }: { id: string; eyebrow: string; title: string; icon: ReactNode; children: ReactNode }) { return <section id={id} className="workspace-section"><header><div>{icon}<span><p className="eyebrow">{eyebrow}</p><h2>{title}</h2></span></div></header>{children}</section> }
function RecordPanel({ title, rows: data, empty }: { title: string; rows: Row[]; empty: string }) { return <section className="panel nested-panel"><header><h3>{title}</h3></header>{data.length ? <div className="record-list">{data.map((row, index) => <div className="record-row" key={String(row.id ?? index)}><div><strong>{String(row.title ?? row.subject ?? row.action ?? row.component ?? row.email ?? row.role ?? "Record")}</strong><small>{String(row.summary ?? row.status ?? row.delivery_status ?? row.reason ?? row.created_at ?? "")}</small></div>{row.status ? <StatusBadge value={row.status}/> : row.is_active != null ? <StatusBadge value={row.is_active ? "ACTIVE" : "INACTIVE"}/> : null}</div>)}</div> : <p className="muted">{empty}</p>}</section> }
