export const permissionCatalog = [
  { code: "ingredients.manage", group: "Inventory", label: "Ingredients" },
  { code: "recipes.manage", group: "Inventory", label: "Recipes & costing" },
  { code: "purchases.manage", group: "Inventory", label: "Purchases" },
  { code: "suppliers.manage", group: "Inventory", label: "Suppliers" },
  { code: "wastage.manage", group: "Inventory", label: "Wastage" },
  { code: "social.manage", group: "Website", label: "Social links" },
  {
    code: "dashboard.view",
    group: "Overview",
    label: "View dashboard",
  },
  {
    code: "pos.use",
    group: "Operations",
    label: "Web POS Counter",
  },
  {
    code: "desktop_pos.use",
    group: "Operations",
    label: "QaziPRO POS Desktop",
  },
  {
    code: "waiter.use",
    group: "Operations",
    label: "Waiter tablet ordering",
  },
  {
    code: "rider.use",
    group: "Operations",
    label: "Rider delivery portal",
  },
  {
    code: "orders.read",
    group: "Operations",
    label: "View orders",
  },
  {
    code: "orders.manage",
    group: "Operations",
    label: "Update order status",
  },
  {
    code: "receipts.print",
    group: "Operations",
    label: "Print receipts / tokens",
  },
  {
    code: "kds.use",
    group: "Operations",
    label: "Kitchen",
  },
  {
    code: "register.manage",
    group: "Operations",
    label: "Register / shifts",
  },
  {
    code: "products.manage",
    group: "Menu",
    label: "Products, gallery & availability",
  },
  {
    code: "categories.manage",
    group: "Menu",
    label: "Categories",
  },
  {
    code: "modifiers.manage",
    group: "Menu",
    label: "Modifiers",
  },
  {
    code: "deals.manage",
    group: "Menu",
    label: "Deals",
  },
  {
    code: "inventory.read",
    group: "Inventory",
    label: "View stock & movements",
  },
  {
    code: "inventory.manage",
    group: "Inventory",
    label: "Adjust stock counts",
  },
  {
    code: "customers.read",
    group: "Customers",
    label: "View customers & history",
  },
  {
    code: "customers.manage",
    group: "Customers",
    label: "Block and unblock customers",
  },
  {
    code: "promotions.manage",
    group: "Customers",
    label: "Coupons / promotions",
  },
  {
    code: "loyalty.manage",
    group: "Customers",
    label: "Loyalty coins & wallets",
  },
  {
    code: "branding.manage",
    group: "Website",
    label: "Branding / logos",
  },
  {
    code: "banners.manage",
    group: "Website",
    label: "Hero & promotional banners",
  },
  {
    code: "content.manage",
    group: "Website",
    label: "Website content",
  },
  {
    code: "reviews.manage",
    group: "Website",
    label: "Review presentation",
  },
  {
    code: "delivery.manage",
    group: "Delivery",
    label: "Areas & delivery rules",
  },
  {
    code: "branches.manage",
    group: "Delivery",
    label: "Branches",
  },
  {
    code: "hours.manage",
    group: "Delivery",
    label: "Opening hours",
  },
  {
    code: "payments.read",
    group: "Finance",
    label: "Payments & transactions",
  },
  {
    code: "payments.refund",
    group: "Finance",
    label: "Refunds",
  },
  {
    code: "reports.read",
    group: "Finance",
    label: "Sales & financial reports",
  },
  {
    code: "invoices.read",
    group: "Finance",
    label: "View invoices",
  },
  {
    code: "invoices.create",
    group: "Finance",
    label: "Create invoices",
  },
  {
    code: "invoices.edit",
    group: "Finance",
    label: "Edit, finalize & void invoices",
  },
  {
    code: "staff.manage",
    group: "Management",
    label: "Staff & roles",
  },
  {
    code: "audit.read",
    group: "Management",
    label: "Audit logs",
  },
  {
    code: "notifications.read",
    group: "Management",
    label: "Notifications",
  },
  {
    code: "business.manage",
    group: "Settings",
    label: "Business profile",
  },
  {
    code: "settings.manage",
    group: "Settings",
    label: "Operating settings, payment configuration & system health",
  },
  {
    code: "printing.manage",
    group: "Settings",
    label: "Invoice & printing settings",
  },
];

export const resourcePermissions: Record<string, string> = {
  products: "products.manage",
  productImages: "products.manage",
  productModifierGroups: "modifiers.manage",
  categories: "categories.manage",
  deals: "deals.manage",
  dealItems: "deals.manage",
  modifierGroups: "modifiers.manage",
  modifierOptions: "modifiers.manage",
  banners: "banners.manage",
  promotionalBanners: "banners.manage",
  promotions: "promotions.manage",
  branches: "branches.manage",
  areas: "delivery.manage",
  deliveryRules: "delivery.manage",
  business: "business.manage",
  appearance: "branding.manage",
  hours: "hours.manage",
  integrations: "reviews.manage",
  settings: "content.manage",
  footerLinks: "content.manage",
  contentPages: "content.manage",
  socialLinks: "social.manage",
  users: "staff.manage",
  audit: "audit.read",
  suppliers: "suppliers.manage",
  ingredients: "ingredients.manage",
  recipes: "recipes.manage",
  stockMovements: "inventory.read",
  printSettings: "printing.manage",
  invoiceSettings: "printing.manage",
  operatingSettings: "settings.manage",
  posSections: "settings.manage",
  posPaymentMethods: "settings.manage",
};
