export type ResourceField = {
  key: string;
  label: string;
  type?:
    | "text"
    | "json"
    | "textarea"
    | "number"
    | "boolean"
    | "datetime"
    | "time"
    | "color"
    | "image"
    | "array"
    | "select"
    | "relation";
  required?: boolean;
  readOnly?: boolean;
  wide?: boolean;
  options?: string[];
  relation?: { table: string; value: string; label: string };
  bucket?: string;
};

export type ResourceConfig = {
  key: string;
  title: string;
  description: string;
  table: string;
  scope: "business" | "branch" | "business-record" | "none";
  fields: ResourceField[];
  columns: string[];
  allowCreate?: boolean;
  allowArchive?: boolean;
  allowDelete?: boolean;
  readOnly?: boolean;
  ownerOnly?: boolean;
  orderBy?: string;
};

export const resources: Record<string, ResourceConfig> = {
  invoiceSettings: {
    key: "invoiceSettings",
    title: "Invoice & receipt template",
    description:
      "Shared business identity, A4/thermal invoice presentation and defaults. Existing thermal printer behavior is unchanged.",
    table: "invoice_settings",
    scope: "business",
    allowCreate: true,
    columns: ["business_name", "invoice_prefix", "currency", "logo_url"],
    fields: [
      {
        key: "logo_url",
        label: "Invoice and receipt logo",
        type: "image",
        bucket: "business-logos",
        wide: true,
      },
      { key: "business_name", label: "business name", required: true },
      { key: "address", label: "address", required: false },
      { key: "phone", label: "phone", required: false },
      { key: "email", label: "email", required: false },
      { key: "tax_number", label: "tax number", required: false },
      { key: "invoice_prefix", label: "invoice prefix", required: true },
      {
        key: "currency",
        label: "Currency",
        type: "select",
        options: ["PKR"],
        required: true,
      },
      { key: "show_logo", label: "Show logo", type: "boolean" },
      { key: "show_address", label: "Show address", type: "boolean" },
      { key: "show_phone", label: "Show phone", type: "boolean" },
      { key: "show_tax", label: "Show tax", type: "boolean" },
      {
        key: "show_customer_address",
        label: "Show customer address",
        type: "boolean",
      },
      {
        key: "show_payment_status",
        label: "Show payment status",
        type: "boolean",
      },
      { key: "show_terms", label: "Show terms", type: "boolean" },
      { key: "thank_you", label: "thank you", type: "textarea", wide: true },
      { key: "terms", label: "terms", type: "textarea", wide: true },
      {
        key: "footer_text",
        label: "footer text",
        type: "textarea",
        wide: true,
      },
    ],
  },
  stockMovements: {
    key: "stockMovements",
    title: "Stock movements",
    description: "Audited purchases, sales, wastage and count adjustments.",
    table: "stock_movements",
    scope: "business",
    readOnly: true,
    orderBy: "created_at",
    columns: [
      "created_at",
      "ingredient_id",
      "movement_type",
      "quantity_delta",
      "unit_cost",
      "reference_type",
      "note",
    ],
    fields: [],
  },
  branches: {
    key: "branches",
    title: "Branches",
    description:
      "Choose restaurant locations from the Delivery setup map. Use this list for branch status and staff-facing details.",
    table: "branches",
    scope: "business",
    allowCreate: true,
    allowArchive: true,
    orderBy: "sort_order",
    columns: [
      "name",
      "code",
      "city",
      "country_code",
      "pickup_enabled",
      "delivery_enabled",
      "temporarily_closed",
      "is_active",
    ],
    fields: [
      { key: "name", label: "Branch name", required: true },
      { key: "code", label: "Branch code", required: true },
      { key: "address", label: "Address", wide: true },
      {
        key: "formatted_address",
        label: "Restaurant location",
        readOnly: true,
        wide: true,
      },
      { key: "city", label: "City / region", required: true },
      { key: "country_code", label: "Country code" },
      { key: "region", label: "Province / state" },
      { key: "phone", label: "Phone" },
      { key: "latitude", label: "Latitude (advanced)", type: "number" },
      { key: "longitude", label: "Longitude (advanced)", type: "number" },
      { key: "timezone", label: "Timezone" },
      {
        key: "online_ordering_enabled",
        label: "Online ordering enabled",
        type: "boolean",
      },
      { key: "pickup_enabled", label: "Pickup enabled", type: "boolean" },
      { key: "delivery_enabled", label: "Delivery enabled", type: "boolean" },
      {
        key: "minimum_prep_minutes",
        label: "Minimum preparation minutes",
        type: "number",
      },
      {
        key: "temporarily_closed",
        label: "Temporarily closed",
        type: "boolean",
      },
      { key: "sort_order", label: "Sort order", type: "number" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
  },
  products: {
    key: "products",
    title: "Products",
    description: "Manage menu items, prices, availability and product media.",
    table: "products",
    scope: "business",
    allowCreate: true,
    allowArchive: true,
    orderBy: "sort_order",
    columns: [
      "name",
      "category_id",
      "base_price",
      "sale_price",
      "is_available",
      "is_featured",
    ],
    fields: [
      { key: "name", label: "Name", required: true },
      { key: "slug", label: "Slug", required: true },
      { key: "sku", label: "SKU / barcode" },
      {
        key: "category_id",
        label: "Category",
        type: "relation",
        required: true,
        relation: { table: "categories", value: "id", label: "name" },
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        wide: true,
      },
      {
        key: "base_price",
        label: "Base price (PKR)",
        type: "number",
        required: true,
      },
      { key: "sale_price", label: "Sale price (PKR)", type: "number" },
      { key: "old_price", label: "Old price (PKR)", type: "number" },
      { key: "badge", label: "Badge" },
      { key: "seo_title", label: "SEO title", wide: true },
      {
        key: "seo_description",
        label: "SEO description",
        type: "textarea",
        wide: true,
      },
      { key: "is_available", label: "Available", type: "boolean" },
      { key: "is_featured", label: "Featured", type: "boolean" },
      { key: "sort_order", label: "Sort order", type: "number" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
  },
  productImages: {
    key: "productImages",
    title: "Product images",
    description: "Upload primary and supporting product photography.",
    table: "product_images",
    scope: "none",
    allowCreate: true,
    allowDelete: true,
    orderBy: "sort_order",
    columns: ["product_id", "url", "alt_text", "is_primary", "sort_order"],
    fields: [
      {
        key: "product_id",
        label: "Product",
        type: "relation",
        required: true,
        relation: { table: "products", value: "id", label: "name" },
      },
      {
        key: "url",
        label: "Image",
        type: "image",
        bucket: "product-images",
        required: true,
        wide: true,
      },
      { key: "alt_text", label: "Alt text", wide: true },
      { key: "is_primary", label: "Primary image", type: "boolean" },
      { key: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  productModifierGroups: {
    key: "productModifierGroups",
    title: "Product modifier assignments",
    description: "Assign reusable customization groups to products.",
    table: "product_modifier_groups",
    scope: "none",
    allowCreate: true,
    allowDelete: true,
    orderBy: "sort_order",
    columns: ["product_id", "modifier_group_id", "sort_order"],
    fields: [
      {
        key: "product_id",
        label: "Product",
        type: "relation",
        required: true,
        relation: { table: "products", value: "id", label: "name" },
      },
      {
        key: "modifier_group_id",
        label: "Modifier group",
        type: "relation",
        required: true,
        relation: { table: "modifier_groups", value: "id", label: "name" },
      },
      { key: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  categories: {
    key: "categories",
    title: "Categories",
    description:
      "Control homepage categories and their optional section presentation.",
    table: "categories",
    scope: "business",
    allowCreate: true,
    allowDelete: true,
    orderBy: "sort_order",
    columns: ["name", "slug", "is_featured", "sort_order", "is_active"],
    fields: [
      { key: "name", label: "Name", required: true },
      { key: "slug", label: "Slug", required: true },
      {
        key: "description",
        label: "Section description (optional)",
        type: "textarea",
        wide: true,
      },
      {
        key: "description_bold",
        label: "Show description in bold",
        type: "boolean",
      },
      {
        key: "image_url",
        label: "Category image",
        type: "image",
        bucket: "category-images",
        wide: true,
      },
      {
        key: "section_banner_url",
        label: "Section banner (optional)",
        type: "image",
        bucket: "category-images",
        wide: true,
      },
      { key: "is_featured", label: "Featured", type: "boolean" },
      { key: "sort_order", label: "Sort order", type: "number" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
  },
  deals: {
    key: "deals",
    title: "Deals",
    description: "Create scheduled, database-backed meal offers.",
    table: "deals",
    scope: "business",
    allowCreate: true,
    allowArchive: true,
    orderBy: "sort_order",
    columns: ["name", "deal_price", "old_price", "is_active", "sort_order"],
    fields: [
      { key: "name", label: "Deal name", required: true },
      { key: "slug", label: "Slug", required: true },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        wide: true,
      },
      {
        key: "image_url",
        label: "Image",
        type: "image",
        bucket: "product-images",
        wide: true,
      },
      {
        key: "deal_price",
        label: "Deal price",
        type: "number",
        required: true,
      },
      { key: "old_price", label: "Old price", type: "number" },
      { key: "starts_at", label: "Starts", type: "datetime" },
      { key: "ends_at", label: "Ends", type: "datetime" },
      { key: "sort_order", label: "Sort order", type: "number" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
  },
  dealItems: {
    key: "dealItems",
    title: "Deal items",
    description: "Document products included in each deal.",
    table: "deal_items",
    scope: "none",
    allowCreate: true,
    allowDelete: true,
    orderBy: "sort_order",
    columns: ["deal_id", "product_id", "quantity", "notes"],
    fields: [
      {
        key: "deal_id",
        label: "Deal",
        type: "relation",
        required: true,
        relation: { table: "deals", value: "id", label: "name" },
      },
      {
        key: "product_id",
        label: "Included product",
        type: "relation",
        relation: { table: "products", value: "id", label: "name" },
      },
      { key: "quantity", label: "Quantity", type: "number", required: true },
      {
        key: "notes",
        label: "Included options / notes",
        type: "textarea",
        wide: true,
      },
      { key: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  modifierGroups: {
    key: "modifierGroups",
    title: "Modifier groups",
    description: "Reusable single or multiple-selection customization groups.",
    table: "modifier_groups",
    scope: "business",
    allowCreate: true,
    allowArchive: true,
    orderBy: "sort_order",
    columns: [
      "name",
      "selection_type",
      "is_required",
      "min_selections",
      "max_selections",
      "is_active",
    ],
    fields: [
      { key: "name", label: "Group name", required: true },
      {
        key: "selection_type",
        label: "Selection type",
        type: "select",
        options: ["SINGLE", "MULTIPLE"],
        required: true,
      },
      { key: "is_required", label: "Required", type: "boolean" },
      { key: "min_selections", label: "Minimum selections", type: "number" },
      { key: "max_selections", label: "Maximum selections", type: "number" },
      { key: "sort_order", label: "Sort order", type: "number" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
  },
  modifierOptions: {
    key: "modifierOptions",
    title: "Modifier options",
    description: "Option labels and authoritative price adjustments.",
    table: "modifier_options",
    scope: "none",
    allowCreate: true,
    allowArchive: true,
    orderBy: "sort_order",
    columns: [
      "name",
      "modifier_group_id",
      "price_adjustment",
      "is_default",
      "is_active",
    ],
    fields: [
      {
        key: "modifier_group_id",
        label: "Modifier group",
        type: "relation",
        required: true,
        relation: { table: "modifier_groups", value: "id", label: "name" },
      },
      { key: "name", label: "Option name", required: true },
      {
        key: "price_adjustment",
        label: "Price adjustment",
        type: "number",
        required: true,
      },
      { key: "is_default", label: "Default", type: "boolean" },
      { key: "sort_order", label: "Sort order", type: "number" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
  },
  banners: {
    key: "banners",
    title: "Hero banners",
    description: "Upload, schedule and reorder image-only homepage slides.",
    table: "hero_banners",
    scope: "business",
    allowCreate: true,
    allowArchive: true,
    orderBy: "sort_order",
    columns: [
      "internal_name",
      "image_url",
      "starts_at",
      "ends_at",
      "is_active",
      "sort_order",
    ],
    fields: [
      { key: "internal_name", label: "Internal name", required: true },
      {
        key: "image_url",
        label: "Desktop banner image",
        type: "image",
        bucket: "hero-banners",
        required: true,
        wide: true,
      },
      {
        key: "mobile_image_url",
        label: "Mobile banner image",
        type: "image",
        bucket: "hero-banners",
        wide: true,
      },
      { key: "alt_text", label: "Accessible alt text", wide: true },
      { key: "starts_at", label: "Starts", type: "datetime" },
      { key: "ends_at", label: "Ends", type: "datetime" },
      { key: "sort_order", label: "Sort order", type: "number" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
  },
  promotionalBanners: {
    key: "promotionalBanners",
    title: "Promotional banners",
    description: "Manage reusable campaign artwork outside the hero carousel.",
    table: "promotional_banners",
    scope: "business",
    allowCreate: true,
    allowArchive: true,
    orderBy: "sort_order",
    columns: [
      "title",
      "image_url",
      "target_url",
      "starts_at",
      "ends_at",
      "is_active",
    ],
    fields: [
      { key: "title", label: "Title", required: true },
      {
        key: "image_url",
        label: "Image",
        type: "image",
        bucket: "hero-banners",
        required: true,
        wide: true,
      },
      { key: "target_url", label: "Target URL", wide: true },
      { key: "starts_at", label: "Starts", type: "datetime" },
      { key: "ends_at", label: "Ends", type: "datetime" },
      { key: "sort_order", label: "Sort order", type: "number" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
  },
  areas: {
    key: "areas",
    title: "Delivery areas",
    description:
      "Review suggested areas or add your own. Customers only see active areas configured for the selected branch.",
    table: "delivery_areas",
    scope: "branch",
    allowCreate: true,
    allowArchive: true,
    orderBy: "sort_order",
    columns: [
      "name",
      "level",
      "city",
      "aliases",
      "boundary_type",
      "sort_order",
      "is_active",
    ],
    fields: [
      {
        key: "level",
        label: "Area level",
        type: "select",
        options: ["CITY", "MAIN_AREA", "SUB_AREA", "LOCALITY", "CUSTOM_ZONE"],
        required: true,
      },
      { key: "parent_id", label: "Parent area ID (advanced)" },
      { key: "city", label: "City / region" },
      { key: "country_code", label: "Country code" },
      {
        key: "boundary_type",
        label: "Coverage method",
        type: "select",
        options: ["LOCALITY_MATCH", "RADIUS", "POLYGON"],
        required: true,
      },
      { key: "center_lat", label: "Centre latitude", type: "number" },
      { key: "center_lng", label: "Centre longitude", type: "number" },
      {
        key: "service_radius_meters",
        label: "Service radius (metres)",
        type: "number",
      },
      {
        key: "boundary_geojson",
        label: "Advanced: Polygon / MultiPolygon GeoJSON (optional)",
        type: "json",
        wide: true,
      },
      { key: "name", label: "Area name", required: true },
      { key: "slug", label: "Slug", required: true },
      {
        key: "aliases",
        label: "Aliases (comma-separated)",
        type: "array",
        wide: true,
      },
      { key: "group_name", label: "Display group", required: true },
      { key: "sort_order", label: "Sort order", type: "number" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
  },
  deliveryRules: {
    key: "deliveryRules",
    title: "Delivery fees",
    description:
      "Choose where you deliver and how delivery fees are calculated. Restaurant origin is saved in the setup map.",
    table: "delivery_rules",
    scope: "branch",
    allowCreate: true,
    orderBy: "created_at",
    columns: [
      "free_distance_km",
      "extra_km_rate",
      "maximum_distance_km",
      "origin_address",
    ],
    fields: [
      {
        key: "free_distance_km",
        label: "Free delivery distance (km)",
        type: "number",
        required: true,
      },
      {
        key: "extra_km_rate",
        label: "Extra kilometre rate (PKR)",
        type: "number",
        required: true,
      },
      {
        key: "maximum_distance_km",
        label: "Maximum delivery distance (km)",
        type: "number",
      },
      {
        key: "rounding_mode",
        label: "Rounding",
        type: "select",
        options: ["CEIL"],
        required: true,
      },
      {
        key: "origin_address",
        label: "Restaurant location",
        readOnly: true,
        wide: true,
      },
      {
        key: "origin_latitude",
        label: "Saved branch latitude",
        type: "number",
        readOnly: true,
      },
      {
        key: "origin_longitude",
        label: "Saved branch longitude",
        type: "number",
        readOnly: true,
      },
    ],
  },
  business: {
    key: "business",
    title: "Business details",
    description: "Core restaurant contact and locale information.",
    table: "businesses",
    scope: "business-record",
    columns: [
      "name",
      "phone",
      "whatsapp",
      "email",
      "city",
      "currency",
      "timezone",
    ],
    fields: [
      { key: "name", label: "Restaurant name", required: true },
      {
        key: "short_description",
        label: "Short description",
        type: "textarea",
        wide: true,
      },
      { key: "phone", label: "Phone" },
      { key: "whatsapp", label: "WhatsApp" },
      { key: "email", label: "Email" },
      { key: "address", label: "Address", wide: true },
      { key: "city", label: "City", required: true },
      {
        key: "currency",
        label: "Currency",
        type: "select",
        options: ["PKR"],
        required: true,
      },
      {
        key: "timezone",
        label: "Timezone",
        type: "select",
        options: ["Asia/Karachi"],
        required: true,
      },
      { key: "is_active", label: "Business active", type: "boolean" },
    ],
  },
  appearance: {
    key: "appearance",
    title: "Brand appearance",
    description:
      "Logo and constrained brand identity shared by customer surfaces.",
    table: "business_branding",
    scope: "business",
    allowCreate: true,
    columns: ["display_name", "logo_url", "primary_color", "secondary_color"],
    fields: [
      { key: "display_name", label: "Brand display name", required: true },
      {
        key: "logo_url",
        label: "Header and modal logo",
        type: "image",
        bucket: "business-logos",
        wide: true,
      },
      {
        key: "footer_logo_url",
        label: "Footer logo",
        type: "image",
        bucket: "business-logos",
        wide: true,
      },
      {
        key: "favicon_url",
        label: "Favicon",
        type: "image",
        bucket: "business-logos",
      },
      {
        key: "primary_color",
        label: "Primary color",
        type: "color",
        required: true,
      },
      {
        key: "secondary_color",
        label: "Secondary color",
        type: "color",
        required: true,
      },
      {
        key: "footer_description",
        label: "Footer description",
        type: "textarea",
        wide: true,
      },
    ],
  },
  hours: {
    key: "hours",
    title: "Opening hours",
    description:
      "Weekly branch hours. Times use the restaurant timezone (Asia/Karachi).",
    table: "business_hours",
    scope: "branch",
    allowCreate: true,
    columns: ["day_of_week", "opens_at", "closes_at", "is_closed"],
    orderBy: "day_of_week",
    fields: [
      {
        key: "day_of_week",
        label: "Day",
        type: "select",
        options: [
          "Sunday",
          "Monday",
          "Tuesday",
          "Wednesday",
          "Thursday",
          "Friday",
          "Saturday",
        ],
        required: true,
      },
      { key: "opens_at", label: "Opens", type: "time" },
      { key: "closes_at", label: "Closes", type: "time" },
      { key: "is_closed", label: "Closed", type: "boolean" },
    ],
  },
  integrations: {
    key: "integrations",
    title: "Review presentation",
    description:
      "Public presentation metadata only. API secrets stay in Vercel environment variables.",
    table: "site_settings",
    scope: "business",
    allowCreate: true,
    columns: [
      "reviews_enabled",
      "reviews_title",
      "reviews_business_name",
      "reviews_widget_id",
    ],
    fields: [
      { key: "reviews_enabled", label: "Show reviews", type: "boolean" },
      { key: "reviews_title", label: "Section title", required: true },
      { key: "reviews_business_name", label: "Business display name" },
      {
        key: "reviews_widget_id",
        label: "Public EmbedSocial widget ID",
        wide: true,
      },
    ],
  },
  settings: {
    key: "settings",
    title: "Site settings",
    description: "Announcement and storefront presentation controls.",
    table: "site_settings",
    scope: "business",
    allowCreate: true,
    columns: ["announcement_enabled", "announcement_text", "reviews_enabled"],
    fields: [
      {
        key: "announcement_enabled",
        label: "Show announcement",
        type: "boolean",
      },
      {
        key: "announcement_text",
        label: "Announcement text",
        type: "textarea",
        wide: true,
      },
      { key: "tagline", label: "Tagline", wide: true },
      { key: "app_store_url", label: "App Store URL (optional)", wide: true },
      {
        key: "play_store_url",
        label: "Google Play URL (optional)",
        wide: true,
      },
      {
        key: "contact_text",
        label: "Contact information",
        type: "textarea",
        wide: true,
      },
      {
        key: "receipt_footer",
        label: "Receipt footer",
        type: "textarea",
        wide: true,
      },
      { key: "reviews_enabled", label: "Show reviews", type: "boolean" },
    ],
  },
  promotions: {
    key: "promotions",
    title: "Coupon promotions",
    description:
      "Configure server-authoritative fixed or percentage discounts.",
    table: "promotions",
    scope: "business",
    allowCreate: true,
    allowArchive: true,
    orderBy: "created_at",
    columns: [
      "code",
      "discount_type",
      "discount_value",
      "maximum_discount",
      "is_active",
    ],
    fields: [
      { key: "code", label: "Code", required: true },
      {
        key: "discount_type",
        label: "Discount type",
        type: "select",
        options: ["FIXED", "PERCENT"],
        required: true,
      },
      {
        key: "discount_value",
        label: "Discount value",
        type: "number",
        required: true,
      },
      { key: "maximum_discount", label: "Maximum discount", type: "number" },
      { key: "starts_at", label: "Starts", type: "datetime" },
      { key: "ends_at", label: "Ends", type: "datetime" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
  },
  socialLinks: {
    key: "socialLinks",
    title: "Social links",
    description:
      "Manage real public social destinations shown with recognizable platform icons in the footer.",
    table: "social_links",
    scope: "business",
    allowCreate: true,
    allowArchive: true,
    orderBy: "sort_order",
    columns: ["platform", "url", "is_active", "sort_order"],
    fields: [
      {
        key: "platform",
        label: "Platform",
        type: "select",
        options: [
          "Facebook",
          "Instagram",
          "TikTok",
          "YouTube",
          "WhatsApp",
          "X",
        ],
        required: true,
      },
      {
        key: "url",
        label: "Public URL (for WhatsApp use https://wa.me/...)",
        required: true,
        wide: true,
      },
      { key: "sort_order", label: "Sort order", type: "number" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
  },
  footerLinks: {
    key: "footerLinks",
    title: "Footer navigation",
    description:
      "Manage footer links by section. Internal links can point to /pages/contact or homepage anchors such as /#menu.",
    table: "footer_links",
    scope: "business",
    allowCreate: true,
    allowArchive: true,
    orderBy: "sort_order",
    columns: ["label", "group_name", "href", "is_active", "sort_order"],
    fields: [
      { key: "label", label: "Link label", required: true },
      {
        key: "group_name",
        label: "Footer group",
        type: "select",
        options: ["QUICK_LINKS", "SUPPORT", "ORDER"],
        required: true,
      },
      { key: "href", label: "Destination", required: true, wide: true },
      { key: "is_external", label: "Open in a new tab", type: "boolean" },
      { key: "sort_order", label: "Sort order", type: "number" },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
  },
  contentPages: {
    key: "contentPages",
    title: "Customer information pages",
    description:
      "Publish Contact, FAQ, Privacy and Terms pages without changing customer code.",
    table: "content_pages",
    scope: "business",
    allowCreate: true,
    allowDelete: true,
    orderBy: "sort_order",
    columns: ["title", "slug", "is_published", "sort_order"],
    fields: [
      { key: "title", label: "Page title", required: true },
      { key: "slug", label: "URL slug", required: true },
      {
        key: "body",
        label: "Page content",
        type: "textarea",
        required: true,
        wide: true,
      },
      { key: "is_published", label: "Published", type: "boolean" },
      { key: "sort_order", label: "Sort order", type: "number" },
    ],
  },
  suppliers: {
    key: "suppliers",
    title: "Suppliers",
    description: "Supplier contact records used by purchasing.",
    table: "suppliers",
    scope: "business",
    allowCreate: true,
    allowArchive: true,
    orderBy: "name",
    columns: ["name", "phone", "email", "is_active"],
    fields: [
      { key: "name", label: "Name", required: true },
      { key: "phone", label: "Phone" },
      { key: "email", label: "Email" },
      { key: "address", label: "Address", type: "textarea", wide: true },
      { key: "notes", label: "Notes", type: "textarea", wide: true },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
  },
  ingredients: {
    key: "ingredients",
    title: "Ingredients",
    description:
      "Branch stock with units, minimum levels and authoritative unit cost.",
    table: "ingredients",
    scope: "business",
    allowCreate: true,
    allowArchive: true,
    orderBy: "name",
    columns: [
      "name",
      "sku",
      "unit",
      "current_stock",
      "minimum_stock",
      "cost_per_unit",
      "is_active",
    ],
    fields: [
      {
        key: "branch_id",
        label: "Branch",
        type: "relation",
        required: true,
        relation: { table: "branches", value: "id", label: "name" },
      },
      {
        key: "supplier_id",
        label: "Primary supplier",
        type: "relation",
        relation: { table: "suppliers", value: "id", label: "name" },
      },
      { key: "name", label: "Name", required: true },
      { key: "sku", label: "SKU" },
      {
        key: "unit",
        label: "Unit",
        type: "select",
        options: ["kg", "g", "litre", "ml", "piece", "pack"],
        required: true,
      },
      {
        key: "current_stock",
        label: "Opening stock",
        type: "number",
        required: true,
      },
      {
        key: "minimum_stock",
        label: "Minimum stock",
        type: "number",
        required: true,
      },
      {
        key: "cost_per_unit",
        label: "Cost per unit (PKR)",
        type: "number",
        required: true,
      },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
  },
  recipes: {
    key: "recipes",
    title: "Recipes / Bill of Materials",
    description: "Map a product or modifier option to ingredient consumption.",
    table: "recipes",
    scope: "business",
    allowCreate: true,
    allowDelete: true,
    orderBy: "created_at",
    columns: ["product_id", "modifier_option_id", "ingredient_id", "quantity"],
    fields: [
      {
        key: "product_id",
        label: "Product (leave blank for option recipe)",
        type: "relation",
        relation: { table: "products", value: "id", label: "name" },
      },
      {
        key: "modifier_option_id",
        label: "Modifier option (leave blank for product recipe)",
        type: "relation",
        relation: { table: "modifier_options", value: "id", label: "name" },
      },
      {
        key: "ingredient_id",
        label: "Ingredient",
        type: "relation",
        required: true,
        relation: { table: "ingredients", value: "id", label: "name" },
      },
      {
        key: "quantity",
        label: "Quantity consumed",
        type: "number",
        required: true,
      },
    ],
  },
  printSettings: {
    key: "printSettings",
    title: "Print settings",
    description:
      "Browser print defaults. Silent printing requires separately selected hardware middleware.",
    table: "print_settings",
    scope: "business",
    allowCreate: true,
    columns: [
      "receipt_width_mm",
      "auto_print_receipt",
      "print_kitchen_ticket",
      "show_prices_on_kitchen_ticket",
      "copies",
    ],
    fields: [
      {
        key: "receipt_width_mm",
        label: "Receipt width",
        type: "select",
        options: ["80", "58"],
        required: true,
      },
      {
        key: "auto_print_receipt",
        label: "Auto-open print after POS sale",
        type: "boolean",
      },
      {
        key: "print_kitchen_ticket",
        label: "Print kitchen ticket",
        type: "boolean",
      },
      {
        key: "show_prices_on_kitchen_ticket",
        label: "Show prices on kitchen ticket",
        type: "boolean",
      },
      {
        key: "receipt_footer",
        label: "Receipt footer",
        type: "textarea",
        wide: true,
      },
      { key: "copies", label: "Copies", type: "number", required: true },
    ],
  },
  operatingSettings: {
    key: "operatingSettings",
    title: "Operating settings",
    description:
      "Kitchen thresholds, rider delivery workflow, POS speed controls and tax configuration.",
    table: "business_operating_settings",
    scope: "business",
    allowCreate: true,
    columns: [
      "rider_portal_enabled",
      "tax_rate_bps",
      "prep_warning_minutes",
      "prep_late_minutes",
      "pos_replacement_window_minutes",
      "pos_recent_order_limit",
    ],
    fields: [
      {
        key: "rider_portal_enabled",
        label: "Enable rider portal and live delivery tracking",
        type: "boolean",
        wide: true,
      },
      {
        key: "tax_rate_bps",
        label: "Tax rate (basis points)",
        type: "number",
        required: true,
      },
      {
        key: "prep_warning_minutes",
        label: "Prep warning minutes",
        type: "number",
        required: true,
      },
      {
        key: "prep_late_minutes",
        label: "Prep late minutes",
        type: "number",
        required: true,
      },
      {
        key: "pos_replacement_window_minutes",
        label: "POS item replacement window (minutes)",
        type: "number",
        required: true,
      },
      {
        key: "pos_recent_order_limit",
        label: "Recent completed POS orders to show (5–50)",
        type: "number",
        required: true,
      },
    ],
  },
  posSections: {
    key: "posSections",
    title: "POS sections",
    description:
      "Create counter departments such as Juice Bar, Desi Kitchen or Chai. Assign each product to its POS section from the Products editor; storefront categories remain independent.",
    table: "pos_sections",
    scope: "business",
    allowCreate: true,
    allowDelete: true,
    orderBy: "sort_order",
    columns: ["name", "description", "color", "sort_order", "is_active"],
    fields: [
      { key: "name", label: "Section name", required: true },
      {
        key: "description",
        label: "Counter description",
        type: "textarea",
        wide: true,
      },
      { key: "color", label: "Section colour", type: "color", required: true },
      {
        key: "sort_order",
        label: "POS display order",
        type: "number",
        required: true,
      },
      { key: "is_active", label: "Show on POS", type: "boolean" },
    ],
  },
  posPaymentMethods: {
    key: "posPaymentMethods",
    title: "POS payment methods",
    description:
      "Choose, name and order checkout buttons. Non-cash sales always record the exact order total; sender/reference details are optional unless you explicitly require them here. Only Cash affects the drawer.",
    table: "pos_payment_methods",
    scope: "business",
    allowCreate: true,
    allowArchive: true,
    orderBy: "sort_order",
    columns: [
      "name",
      "code",
      "kind",
      "requires_reference",
      "is_active",
      "sort_order",
    ],
    fields: [
      { key: "name", label: "Checkout button name", required: true },
      {
        key: "code",
        label: "Unique code (A–Z, numbers, underscore)",
        required: true,
      },
      {
        key: "kind",
        label: "Payment kind",
        type: "select",
        options: ["CASH", "WALLET", "CARD", "OTHER"],
        required: true,
      },
      {
        key: "requires_reference",
        label: "Make sender / transaction reference required",
        type: "boolean",
      },
      {
        key: "sort_order",
        label: "Checkout order",
        type: "number",
        required: true,
      },
      { key: "is_active", label: "Active", type: "boolean" },
    ],
  },
  audit: {
    key: "audit",
    title: "Audit logs",
    description: "Immutable records of important administrative changes.",
    table: "audit_logs",
    scope: "business",
    readOnly: true,
    orderBy: "created_at",
    columns: ["created_at", "actor_id", "action", "entity_type", "entity_id"],
    fields: [],
  },
};
