import { Smartphone } from "lucide-react"
import { upsertMobileAppAction } from "@/app/actions"
import { OperationsTable } from "@/components/operations-table"
import { PlatformShell } from "@/components/platform-shell"
import { DataNotice, PageHeader } from "@/components/ui"
import { requirePlatformStaff } from "@/lib/auth"
import { getModuleRows, getPlatformBusinessOptions } from "@/lib/data"

export default async function AppsPage({ searchParams }: { searchParams: Promise<Record<string,string|undefined>> }) {
  const context=await requirePlatformStaff(),notice=await searchParams
  const [result,businesses]=await Promise.all([getModuleRows("apps",Number(notice.page??1)),getPlatformBusinessOptions()])
  return <PlatformShell context={context}><PageHeader eyebrow="WHITE-LABEL REGISTRY" title="Android and iOS apps" description="One master codebase, tenant-safe public key and unique store identifiers per restaurant."/>{result.error||businesses.error?<DataNotice message={result.error??businesses.error??"Data unavailable"}/>:null}{notice.saved?<div className="success-banner">App registry updated and audited.</div>:null}{notice.error?<div className="form-error">App configuration rejected safely ({notice.error}).</div>:null}<section className="panel"><header><div><p className="eyebrow">APP CONFIGURATION</p><h2>Register release identity</h2></div><Smartphone/></header><form action={upsertMobileAppAction} className="form-grid compact-form"><label>Restaurant<select name="businessId" required><option value="">Select restaurant</option>{businesses.data.map((item)=><option key={String(item.id)} value={String(item.id)}>{String(item.name)}</option>)}</select></label><label>Platform<select name="platform"><option>ANDROID</option><option>IOS</option></select></label><label>App name<input name="appName" required/></label><label>Application / Bundle ID<input name="applicationIdentifier" placeholder="com.qazipro.restaurant" required/></label><label>Version<input name="versionName" placeholder="1.0.0"/></label><label>Build number<input name="buildNumber" type="number" min="1"/></label><label>Credential status<select name="credentialStatus"><option>MISSING</option><option>INVALID</option><option>NEEDS_REVIEW</option><option>DISABLED</option></select></label><label>Release status<select name="releaseStatus"><option>CONFIGURATION</option><option>CREDENTIALS_REQUIRED</option><option>UPDATE_REQUIRED</option><option>FAILED</option></select></label><label>Store URL<input name="storeUrl" type="url"/></label><label className="check-row span-2"><input name="enabled" type="checkbox"/>Purchased / enabled</label><label className="span-2">Audit reason<input name="reason" required defaultValue="White-label app configuration"/></label><button className="button span-2"><Smartphone/>Save app registry</button></form></section><OperationsTable rows={result.data} page={result.page} count={result.count} pageSize={result.pageSize} href="/apps" columns={["app_name","businesses","platform","application_identifier","credential_status","push_status","release_status","version_name"]} empty="No mobile apps registered"/></PlatformShell>
}
